export const settingsLang = {
  en: {
    title: 'Settings & Security',
    subtitle: 'Manage your personal profile, security options, and preferences.',
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    phone: 'Phone Number',
    security: 'Security & 2FA',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    twoFactor: 'Two-Factor Authentication (2FA)',
    twoFactorDesc: 'Require SMS or authenticator code on sensitive actions.',
    saveChanges: 'Save Changes',
    saved: 'Settings saved successfully!',
    maxFileSize: 'Maximum file size is 10 MB.',
    avatarUploadError: 'Avatar upload error',
    processingAvatar: 'Processing (ImageSharp)...',
    changeAvatar: 'Change Avatar',
    fullName: 'Full Name',
    updatePasswordDesc: 'Update your account password regularly to keep your funds safe.',
    updatePasswordBtn: 'Update Password',
    cancel: 'Cancel',
    fillAllFields: 'All fields must be filled',
    passwordTooShort: 'Password must be at least 8 characters',
    newPasswordSameAsOld: 'New password cannot be the current password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordChanged: 'Password successfully changed!',
    emailVerified: 'Email verified',
    emailNotVerified: 'Email not verified',
    verifyEmailNow: 'Verify now',
    twoFactorEnabled: '2FA enabled successfully',
    twoFactorDisabled: '2FA disabled',
    twoFactorError: 'Failed to update 2FA setting'
  },
  az: {
    title: 'Parametrlər və Təhlükəsizlik',
    subtitle: 'Şəxsi profilinizi, təhlükəsizlik seçimlərinizi və tənzimləmələrinizi idarə edin.',
    personalInfo: 'Şəxsi Məlumatlar',
    firstName: 'Adınız',
    lastName: 'Soyadınız',
    email: 'E-poçt ünvanı',
    phone: 'Telefon nömrəsi',
    security: 'Təhlükəsizlik və 2FA',
    changePassword: 'Şifrəni Dəyişdir',
    currentPassword: 'Cari Şifrə',
    newPassword: 'Yeni Şifrə',
    confirmPassword: 'Yeni Şifrəni Təsdiqləyin',
    twoFactor: 'İki-Mərhələli Doğrulama (2FA)',
    twoFactorDesc: 'Həssas əməliyyatlarda SMS və ya autentifikator kodu tələb olunsun.',
    saveChanges: 'Dəyişiklikləri Yadda Saxla',
    saved: 'Parametrlər uğurla yadda saxlanıldı!',
    maxFileSize: 'Maksimum fayl ölçüsü 10 MB-dır.',
    avatarUploadError: 'Avatar yükləmə xətası',
    processingAvatar: 'İşlənir (ImageSharp)...',
    changeAvatar: 'Avatarı Dəyiş',
    fullName: 'Tam Adınız',
    updatePasswordDesc: 'Vəsaitlərinizi təhlükəsiz saxlamaq üçün hesabınızın şifrəsini müntəzəm olaraq yeniləyin.',
    updatePasswordBtn: 'Şifrəni Yenilə',
    cancel: 'Ləğv et',
    fillAllFields: 'Bütün sahələr doldurulmalıdır',
    passwordTooShort: 'Şifrə ən azı 8 simvol olmalıdır',
    newPasswordSameAsOld: 'Yeni şifrə cari şifrə ilə eyni ola bilməz',
    passwordsDoNotMatch: 'Şifrələr uyğun gəlmir',
    passwordChanged: 'Şifrə uğurla dəyişdirildi!',
    emailVerified: 'E-poçt təsdiqlənib',
    emailNotVerified: 'E-poçt təsdiqlənməyib',
    verifyEmailNow: 'İndi təsdiqlə',
    twoFactorEnabled: '2FA uğurla aktivləşdirildi',
    twoFactorDisabled: '2FA söndürüldü',
    twoFactorError: '2FA parametrini yeniləmək alınmadı'
  },
  ru: {
    title: 'Настройки и безопасность',
    subtitle: 'Управление личным профилем, параметрами безопасности и настройками.',
    personalInfo: 'Личная информация',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Эл. почта',
    phone: 'Номер телефона',
    security: 'Безопасность и 2FA',
    changePassword: 'Сменить пароль',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите новый пароль',
    twoFactor: 'Двухфакторная аутентификация (2FA)',
    twoFactorDesc: 'Запрашивать код из SMS или приложения при важных операциях.',
    saveChanges: 'Сохранить изменения',
    saved: 'Настройки успешно сохранены!',
    maxFileSize: 'Максимальный размер файла — 10 МБ.',
    avatarUploadError: 'Ошибка загрузки аватара',
    processingAvatar: 'Обработка (ImageSharp)...',
    changeAvatar: 'Изменить аватар',
    fullName: 'Полное имя',
    updatePasswordDesc: 'Регулярно обновляйте пароль, чтобы ваши средства были в безопасности.',
    updatePasswordBtn: 'Сменить пароль',
    cancel: 'Отмена',
    fillAllFields: 'Все поля должны быть заполнены',
    passwordTooShort: 'Пароль должен состоять минимум из 8 символов',
    newPasswordSameAsOld: 'Новый пароль не может совпадать с текущим',
    passwordsDoNotMatch: 'Пароли не совпадают',
    passwordChanged: 'Пароль успешно изменен!',
    emailVerified: 'Email подтверждён',
    emailNotVerified: 'Email не подтверждён',
    verifyEmailNow: 'Подтвердить сейчас',
    twoFactorEnabled: '2FA успешно включён',
    twoFactorDisabled: '2FA отключён',
    twoFactorError: 'Не удалось изменить настройку 2FA'
  }
}
