export const settingsLang = {
  en: {
    title: 'Settings & Security',
    subtitle: 'Manage your personal profile, security options, and preferences.',
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    phone: 'Phone Number',
    security: 'Security & 2FA',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    twoFactor: 'Two-Factor Authentication (2FA)',
    twoFactorDesc: 'Require SMS or authenticator code on sensitive actions.',
    saveChanges: 'Save Changes',
    saved: 'Settings saved successfully!'
  },
  az: {
    title: 'Parametrlər və Təhlükəsizlik',
    subtitle: 'Şəxsi profilinizi, təhlükəsizlik seçimlərinizi və tənzimləmələrinizi idarə edin.',
    personalInfo: 'Şəxsi Məlumatlar',
    firstName: 'Adınız',
    lastName: 'Soyadınız',
    email: 'E-poçt ünvanı',
    phone: 'Telefon nömrəsi',
    security: 'Təhlükəsizlik və 2FA',
    changePassword: 'Şifrəni Dəyişdir',
    currentPassword: 'Cari Şifrə',
    newPassword: 'Yeni Şifrə',
    confirmPassword: 'Yeni Şifrəni Təsdiqləyin',
    twoFactor: 'İki-Mərhələli Doğrulama (2FA)',
    twoFactorDesc: 'Həssas əməliyyatlarda SMS və ya autentifikator kodu tələb olunsun.',
    saveChanges: 'Dəyişiklikləri Yadda Saxla',
    saved: 'Parametrlər uğurla yadda saxlanıldı!'
  },
  ru: {
    title: 'Настройки и безопасность',
    subtitle: 'Управление личным профилем, параметрами безопасности и настройками.',
    personalInfo: 'Личная информация',
    firstName: 'Имя',
    lastName: 'Фамилия',
    email: 'Эл. почта',
    phone: 'Номер телефона',
    security: 'Безопасность и 2FA',
    changePassword: 'Сменить пароль',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите новый пароль',
    twoFactor: 'Двухфакторная аутентификация (2FA)',
    twoFactorDesc: 'Запрашивать код из SMS или приложения при важных операциях.',
    saveChanges: 'Сохранить изменения',
    saved: 'Настройки успешно сохранены!'
  }
}
