export const authLang = {
  en: {
    navHome: 'Home',
    navLoans: 'Loans',
    navCashback: 'Cashback',
    navSupport: 'Support',
    signIn: 'Sign in',
    openAccount: 'Open account',
    loginTitle: 'Sign in to NeoBank',
    loginDesc: 'Access your accounts, cards, and daily financial operations.',
    emailLabel: 'Email address',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginSubmit: 'Sign in',
    noAccount: "Don't have an account?",
    signUpNow: 'Open an account',
    registerTitle: 'Open your NeoBank account',
    registerDesc: 'Join thousands of clients enjoying premium digital banking.',
    firstNameLabel: 'First name',
    firstNamePlaceholder: 'John',
    lastNameLabel: 'Last name',
    lastNamePlaceholder: 'Doe',
    confirmPasswordLabel: 'Confirm password',
    confirmPasswordPlaceholder: 'Re-enter your password',
    termsAgreement: 'I agree to the Terms of Service and Privacy Policy',
    registerSubmit: 'Create account',
    hasAccount: 'Already have an account?',
    signInNow: 'Sign in',
    feat1Title: 'Two-factor authentication',
    feat1Text: '2FA is enabled on every sensitive action to keep your account protected.',
    feat2Title: 'Instant card control',
    feat2Text: 'Freeze your card, change limits, and manage settings in real time.',
    feat3Title: '24/7 account access',
    feat3Text: 'View balances, transactions, and cashback rewards at any time, from anywhere.',
    regFeat1Title: 'Open an account in 2 minutes',
    regFeat1Text: 'Complete registration online with no paperwork and no branch visit required.',
    regFeat2Title: 'Up to 100% cashback',
    regFeat2Text: 'Earn automatic rewards at supermarkets, fuel stations, pharmacies, and more.',
    regFeat3Title: 'Loans from 9.9% per year',
    regFeat3Text: 'Apply online and receive a pre-check decision in under 2 minutes.',
    invalidCredentials: 'Invalid email or password.',
    accountDisabled: 'Your account has been blocked. Please contact support.',
    accountNotFound: 'Account not found.',
    serverError: 'An unexpected server error occurred. Please try again later.'
  },
  az: {
    navHome: 'Ana səhifə',
    navLoans: 'Kreditlər',
    navCashback: 'Kəşbək',
    navSupport: 'Dəstək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    loginTitle: 'NeoBank-a daxil olun',
    loginDesc: 'Hesablarınıza, kartlarınıza və gündəlik maliyyə əməliyyatlarınıza daxil olun.',
    emailLabel: 'E-poçt ünvanı',
    emailPlaceholder: 'ad@misal.com',
    passwordLabel: 'Şifrə',
    passwordPlaceholder: 'Şifrənizi daxil edin',
    rememberMe: 'Məni xatırla',
    forgotPassword: 'Şifrəni unutmusunuz?',
    loginSubmit: 'Daxil ol',
    noAccount: 'Hesabınız yoxdur?',
    signUpNow: 'Hesab açın',
    registerTitle: 'NeoBank hesabınızı açın',
    registerDesc: 'Premium rəqəmsal bankçılıqdan həzz alan minlərlə müştəriyə qoşulun.',
    firstNameLabel: 'Adınız',
    firstNamePlaceholder: 'Əli',
    lastNameLabel: 'Soyadınız',
    lastNamePlaceholder: 'Məmmədov',
    confirmPasswordLabel: 'Şifrəni təsdiqləyin',
    confirmPasswordPlaceholder: 'Şifrəni təkrar daxil edin',
    termsAgreement: 'Xidmət Şərtləri və Məfhilik Siyasəti ilə razılaşıram',
    registerSubmit: 'Hesab yaradın',
    hasAccount: 'Artıq hesabınız var?',
    signInNow: 'Daxil olun',
    feat1Title: 'İkiFA doğrulama',
    feat1Text: 'Hesabınızı qorumaq üçün hər həssas əməliyyatda 2FA aktivdir.',
    feat2Title: 'Anında kart nəzarəti',
    feat2Text: 'Kartınızı dondurun, limitləri dəyişin və parametri real vaxtda idarə edin.',
    feat3Title: '24/7 hesab girişi',
    feat3Text: 'İstənilən vaxt, istənilən yerdən balansları, əməliyyatları və kəşbəki görün.',
    regFeat1Title: '2 dəqiqəyə hesab açın',
    regFeat1Text: 'Sənədsiz və filiala getmədən onlayn qeydiyyatı tamamlayın.',
    regFeat2Title: '100%-dək kəşbək',
    regFeat2Text: 'Supermarketlərdə, yanacaqdoldurma məntəqələrində və apteklərdə avtomatik mükafatlar qazanın.',
    regFeat3Title: 'İllik 9.9%-dən kreditlər',
    regFeat3Text: 'Onlayn müraciət edin və 2 dəqiqədən az müddətdə ön yoxlama qərarı alın.',
    invalidCredentials: 'E-poçt ünvanı və ya şifrə yanlışdır.',
    accountDisabled: 'Hesabınız bloklanıb. Zəhmət olmasa dəstək xidməti ilə əlaqə saxlayın.',
    accountNotFound: 'Hesab tapılmadı.',
    serverError: 'Gözlənilməz server xətası baş verdi. Zəhmət olmasa daha sonra yenidən cəhd edin.'
  },
  ru: {
    navHome: 'Главная',
    navLoans: 'Кредиты',
    navCashback: 'Кэшбэк',
    navSupport: 'Поддержка',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    loginTitle: 'Вход в NeoBank',
    loginDesc: 'Доступ к вашим счетам, картам и ежедневным операциям.',
    emailLabel: 'Эл. почта',
    emailPlaceholder: 'name@example.com',
    passwordLabel: 'Пароль',
    passwordPlaceholder: 'Введите пароль',
    rememberMe: 'Запомнить меня',
    forgotPassword: 'Забыли пароль?',
    loginSubmit: 'Войти',
    noAccount: 'Еще нет аккаунта?',
    signUpNow: 'Зарегистрироваться',
    registerTitle: 'Регистрация в NeoBank',
    registerDesc: 'Присоединяйтесь к тысячам клиентов премиального онлайн-банка.',
    firstNameLabel: 'Имя',
    firstNamePlaceholder: 'Иван',
    lastNameLabel: 'Фамилия',
    lastNamePlaceholder: 'Иванов',
    confirmPasswordLabel: 'Подтверждение пароля',
    confirmPasswordPlaceholder: 'Повторите пароль',
    termsAgreement: 'Я согласен с Условиями использования и Политикой конфиденциальности',
    registerSubmit: 'Создать аккаунт',
    hasAccount: 'Уже есть аккаунт?',
    signInNow: 'Войти',
    feat1Title: 'Двухфакторная защита',
    feat1Text: '2FA активна для всех важных операций для максимальной защиты.',
    feat2Title: 'Мгновенный контроль карт',
    feat2Text: 'Замораживайте карту и меняйте лимиты в реальном времени.',
    feat3Title: 'Доступ 24/7',
    feat3Text: 'Отслеживайте балансы, переводы и кэшбэк в любое время.',
    regFeat1Title: 'Открытие счета за 2 минуты',
    regFeat1Text: 'Быстрая онлайн-регистрация без визита в офис.',
    regFeat2Title: 'Кэшбэк до 100%',
    regFeat2Text: 'Автоматические бонусы в супермаркетах, АЗС и аптеках.',
    regFeat3Title: 'Кредиты от 9.9% годовых',
    regFeat3Text: 'Подайте заявку онлайн и получите решение за 2 минуты.',
    invalidCredentials: 'Неверный адрес электронной почты или пароль.',
    accountDisabled: 'Ваш аккаунт заблокирован. Пожалуйста, обратитесь в поддержку.',
    accountNotFound: 'Аккаунт не найден.',
    serverError: 'Произошла непредвиденная ошибка сервера. Пожалуйста, повторите попытку позже.'
  }
}
