export const verifyModalLang = {
  en: {
    verifyEmailTitle: 'Confirm Your Email',
    verifyEmailDesc: 'We sent a 7-digit verification code to',
    twoFactorTitle: 'Two-Factor Authentication',
    twoFactorDesc: 'Enter the 7-digit code sent to',
    enterFullCode: 'Please enter all 7 digits',
    invalidCode: 'Invalid or expired code. Please try again.',
    confirmBtn: 'Confirm Code',
    didntReceive: "Didn't receive it?",
    resendCode: 'Resend code',
    resendIn: 'Resend in',
    resendError: 'Failed to resend code. Please try again.',
    codeExpiry: 'The code is valid for 15 minutes.',
  },
  az: {
    verifyEmailTitle: 'E-poçtunuzu Təsdiqləyin',
    verifyEmailDesc: 'Aşağıdakı ünvana 7 rəqəmli kod göndərdik:',
    twoFactorTitle: 'İki-Mərhələli Doğrulama',
    twoFactorDesc: 'Aşağıdakı ünvana göndərilən 7 rəqəmli kodu daxil edin:',
    enterFullCode: 'Xahiş edirik bütün 7 rəqəmi daxil edin',
    invalidCode: 'Kod yanlış və ya vaxtı bitib. Yenidən cəhd edin.',
    confirmBtn: 'Kodu Təsdiqlə',
    didntReceive: 'Almadınız?',
    resendCode: 'Yenidən göndər',
    resendIn: 'Sonra göndər:',
    resendError: 'Kod göndərmək alınmadı. Yenidən cəhd edin.',
    codeExpiry: 'Kod 15 dəqiqə ərzində etibarlıdır.',
  },
  ru: {
    verifyEmailTitle: 'Подтвердите Email',
    verifyEmailDesc: 'Мы отправили 7-значный код на',
    twoFactorTitle: 'Двухфакторная аутентификация',
    twoFactorDesc: 'Введите 7-значный код, отправленный на',
    enterFullCode: 'Пожалуйста, введите все 7 цифр',
    invalidCode: 'Неверный или истёкший код. Попробуйте снова.',
    confirmBtn: 'Подтвердить код',
    didntReceive: 'Не получили?',
    resendCode: 'Отправить снова',
    resendIn: 'Повторить через',
    resendError: 'Не удалось отправить код. Попробуйте снова.',
    codeExpiry: 'Код действителен 15 минут.',
  },
}
