export const cardsLang = {
  en: {
    navHome: 'Home',
    navLoans: 'Loans',
    navDeposits: 'Deposits',
    navCashback: 'Cashback',
    navSupport: 'Support',
    signIn: 'Sign in',
    openAccount: 'Open account',
    heroEyebrow: 'NeoBank Cards',
    heroTitle: 'Choose the card that fits how you spend.',
    compareCards: 'Compare cards',
    orderCard: 'Order a card',
    stat0Label: 'Issue time',
    stat0Sub: 'digital card',
    stat1Label: 'Networks',
    stat1Sub: 'choose anytime',
    stat2Label: 'Cashback',
    stat2Sub: 'selected categories',
    stat3Label: 'Controls',
    stat3Sub: 'freeze and settings',
    mediaCopy: 'Issue Visa or Mastercard, manage settings, track activity, and keep card control close to every payment.',
    lineupEyebrow: 'Card lineup',
    lineupTitle: 'Visa first, Mastercard one swipe away.',
    lineupDesc: 'Each card starts with the Visa design. Switch the network control to compare the Mastercard version without leaving the offer.',
    card0Eyebrow: 'Everyday card',
    card0Title: 'Standard keeps daily spending clear.',
    card0Text: 'A practical card for salary, transfers, online payments, and regular shopping with simple controls in NeoBank.',
    card0Feature: '100% cashback',
    card0Service: '0 AZN monthly',
    card1Eyebrow: 'Priority banking',
    card1Title: 'Elite gives your main card room to move.',
    card1Text: 'For larger purchases and priority customers: priority privileges, premium support, and stronger everyday payment control.',
    card1Feature: '2x VAT return',
    card1Service: '9 AZN monthly',
    card2Eyebrow: 'Travel and lifestyle',
    card2Title: 'Premium adds richer comfort and flexible benefits.',
    card2Text: 'Built for active spending: travel-ready payments, VIP services, and card settings you can adjust before checkout.',
    card2Feature: 'VIP services',
    card2Service: '19 AZN monthly',
    specialFeature: 'Special feature',
    service: 'Service',
    orderThisCard: 'Order this card',
    cardDetails: 'Card details'
  },
  az: {
    navHome: 'Ana səhifə',
    navLoans: 'Kreditlər',
    navDeposits: 'Depozitlər',
    navCashback: 'Kəşbək',
    navSupport: 'Dəstək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    heroEyebrow: 'NeoBank Kartları',
    heroTitle: 'Xərcləmənizə uyğun kartı seçin.',
    compareCards: 'Kartları müqayisə et',
    orderCard: 'Kart sifariş et',
    stat0Label: 'Verilmə müddəti',
    stat0Sub: 'rəqəmsal kart',
    stat1Label: 'Şəbəkələr',
    stat1Sub: 'istənilən vaxt seçin',
    stat2Label: 'Kəşbək',
    stat2Sub: 'seçilmiş kateqoriyalar',
    stat3Label: 'Nəzarət',
    stat3Sub: 'dondurma və parametrlər',
    mediaCopy: 'Visa və ya Mastercard buraxın, parametrləri idarə edin, fəallığı izləyin və kart nəzarətini hər ödənişə yaxın saxlayın.',
    lineupEyebrow: 'Kart çeşidi',
    lineupTitle: 'İstər Visa, istər Mastercard.',
    lineupDesc: 'Hər bir kart Visa dizaynı ilə başlayır. Təklifdən ayrılmadan Mastercard versiyasını müqayisə etmək üçün şəbəkəni dəyişin.',
    card0Eyebrow: 'Gündəlik kart',
    card0Title: 'Standard gündəlik xərcləri aydın saxlayır.',
    card0Text: 'Maaş, köçürmələr, onlayn ödənişlər və NeoBank-da sadə nəzarətlə müntəzəm alış-veriş üçün praktiki kart.',
    card0Feature: '100% kəşbək',
    card0Service: '0 AZN aylıq',
    card1Eyebrow: 'Prioritet bankçılıq',
    card1Title: 'Elite əsas kartınıza daha çox imkan verir.',
    card1Text: 'Böyük alış-verişlər və prioritet müştərilər üçün: prioritet imtiyazlar, premium dəstək və daha güclü gündəlik ödəniş nəzarəti.',
    card1Feature: '2x ƏDV geri al',
    card1Service: '9 AZN aylıq',
    card2Eyebrow: 'Səyahət və həyat tərzi',
    card2Title: 'Premium zəngin rahatlıq və çevik üstünlüklər əlavə edir.',
    card2Text: 'Fəal xərcləmələr üçün hazırlanmışdır: səyahətə hazır ödənişlər, VIP xidmətlər və ödənişdən əvvəl tənzimləyə biləcəyiniz kart parametrləri.',
    card2Feature: 'VIP xidmətlər',
    card2Service: '19 AZN aylıq',
    specialFeature: 'Xüsusi üstünlük',
    service: 'Xidmət haqqı',
    orderThisCard: 'Bu kartı sifariş et',
    cardDetails: 'Kart təfərrüatları'
  },
  ru: {
    navHome: 'Главная',
    navLoans: 'Кредиты',
    navDeposits: 'Вклады',
    navCashback: 'Кэшбэк',
    navSupport: 'Поддержка',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    heroEyebrow: 'Карты NeoBank',
    heroTitle: 'Выберите карту под ваши финансовые цели.',
    compareCards: 'Сравнить карты',
    orderCard: 'Заказать карту',
    stat0Label: 'Выпуск карты',
    stat0Sub: 'цифровая карта',
    stat1Label: 'Платежные системы',
    stat1Sub: 'выбор в любое время',
    stat2Label: 'Кэшбэк',
    stat2Sub: 'избранные категории',
    stat3Label: 'Контроль',
    stat3Sub: 'заморозка и настройки',
    mediaCopy: 'Выпускайте Visa или Mastercard, управляйте настройками, отслеживайте историю и контролируйте каждый платеж.',
    lineupEyebrow: 'Линейка карт',
    lineupTitle: 'Visa или Mastercard — в один клик.',
    lineupDesc: 'Каждая карта доступна в формате Visa. Переключайте платежную систему, чтобы сравнить условия не выходя из меню.',
    card0Eyebrow: 'Карта на каждый день',
    card0Title: 'Standard делает повседневные расходы прозрачными.',
    card0Text: 'Практичная карта для зарплаты, переводов, покупок в интернете и привычных трат с простым управлением.',
    card0Feature: '100% кэшбэк',
    card0Service: '0 AZN в месяц',
    card1Eyebrow: 'Приоритетный банкинг',
    card1Title: 'Elite дает вашей основной карте максимум свободы.',
    card1Text: 'Для крупных покупок и премиальных клиентов: привилегии, персональная поддержка и усиленный контроль трат.',
    card1Feature: '2x возврат НДС',
    card1Service: '9 AZN в месяц',
    card2Eyebrow: 'Путешествия и стиль',
    card2Title: 'Premium добавляет повышенный комфорт и гибкие бонусы.',
    card2Text: 'Создана для активных трат: платежи по всему миру, VIP-сервисы и персональные настройки карты.',
    card2Feature: 'VIP-сервисы',
    card2Service: '19 AZN в месяц',
    specialFeature: 'Особенность',
    service: 'Обслуживание',
    orderThisCard: 'Заказать эту карту',
    cardDetails: 'Подробнее о карте'
  }
}
