export const footerLang = {
  en: {
    contactUs: 'Contact Us',
    address: 'Address',
    addressValue: 'Baku, Azerbaijan',
    mailUs: 'Mail us',
    phone: 'Phone',
    products: 'Products',
    cards: 'Cards',
    loans: 'Loans',
    deposits: 'Deposits',
    cashback: 'Cashback',
    information: 'Information',
    home: 'Home',
    signIn: 'Sign in',
    openAccount: 'Open account',
    support: 'Support',
    subscribe: 'Subscribe',
    emailPlaceholder: 'Email address',
    subscribeBtn: 'Subscribe',
    copyrightPart1: 'Copyright 2026 ',
    copyrightPart2: '. All Rights Reserved',
    appEyebrow: 'NeoBank mobile',
    appTitle: 'Download the app and track your actions with comfort.',
    appDesc: 'Manage daily banking in one place: monitor balances, card activity, cashback, deposits and support updates with a calmer mobile experience.',
    feat1Title: 'Track actions',
    feat1Text: 'See payments, transfers and cashback in one place.',
    feat2Title: 'Control cards',
    feat2Text: 'Freeze cards and check limits anytime.',
    feat3Title: 'Stay updated',
    feat3Text: 'Follow deposits, loans and support updates faster.'
  },
  az: {
    contactUs: 'Əlaqə',
    address: 'Ünvan',
    addressValue: 'Bakı, Azərbaycan',
    mailUs: 'E-poçt',
    phone: 'Telefon',
    products: 'Məhsullar',
    cards: 'Kartlar',
    loans: 'Kreditlər',
    deposits: 'Depozitlər',
    cashback: 'Kəşbək',
    information: 'Məlumat',
    home: 'Ana səhifə',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    support: 'Dəstək',
    subscribe: 'Abunə ol',
    emailPlaceholder: 'E-poçt ünvanı',
    subscribeBtn: 'Abunə ol',
    copyrightPart1: 'Müəllif hüquqları © 2026 ',
    copyrightPart2: '. Bütün hüquqlar qorunur',
    appEyebrow: 'NeoBank mobil',
    appTitle: 'Tətbiqi yükləyin və əməliyyatlarınızı rahatlıqla izləyin.',
    appDesc: 'Gündəlik bankçılığı bir yerdə idarə edin: balansları, kart fəallığını, kəşbəki, depozitləri və dəstək yeniləmələrini daha rahat mobil təcrübə ilə izləyin.',
    feat1Title: 'Əməliyyatları izləyin',
    feat1Text: 'Ödənişləri, köçürmələri və kəşbəki bir yerdə görün.',
    feat2Title: 'Kartlara nəzarət',
    feat2Text: 'İstənilən vaxt kartları dondurun və limitləri yoxlayın.',
    feat3Title: 'Yeniliklərdən xəbərdar olun',
    feat3Text: 'Depozit, kredit və dəstək yeniləmələrini daha sürətli izləyin.'
  },
  ru: {
    contactUs: 'Контакты',
    address: 'Адрес',
    addressValue: 'Баку, Азербайджан',
    mailUs: 'Написать нам',
    phone: 'Телефон',
    products: 'Продукты',
    cards: 'Карты',
    loans: 'Кредиты',
    deposits: 'Вклады',
    cashback: 'Кэшбэк',
    information: 'Информация',
    home: 'Главная',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    support: 'Поддержка',
    subscribe: 'Подписаться',
    emailPlaceholder: 'Адрес эл. почты',
    subscribeBtn: 'Подписаться',
    copyrightPart1: 'Авторские права © 2026 ',
    copyrightPart2: '. Все права защищены',
    appEyebrow: 'NeoBank мобильный',
    appTitle: 'Скачайте приложение и контролируйте финансы с комфортом.',
    appDesc: 'Управляйте ежедневным банкингом в одном месте: отслеживайте балансы, действия по картам, кэшбэк, вклады и обращения в поддержку.',
    feat1Title: 'Отслеживайте операции',
    feat1Text: 'Смотрите платежи, переводы и кэшбэк в одном месте.',
    feat2Title: 'Управляйте картами',
    feat2Text: 'Замораживайте карты и проверяйте лимиты в любое время.',
    feat3Title: 'Будьте в курсе',
    feat3Text: 'Следите за депозитами, кредитами и обновлениями поддержки.'
  }
}
