export const footerLang = {
  en: {
    contactUs: 'Contact Us',
    address: 'Address',
    addressValue: 'Baku, Azerbaijan',
    mailUs: 'Mail us',
    phone: 'Phone',
    products: 'Products',
    cards: 'Cards',
    loans: 'Loans',
    deposits: 'Deposits',
    cashback: 'Cashback',
    information: 'Information',
    home: 'Home',
    signIn: 'Sign in',
    openAccount: 'Open account',
    support: 'Support',
    subscribe: 'Subscribe',
    emailPlaceholder: 'Email address',
    subscribeBtn: 'Subscribe',
    copyrightPart1: 'Copyright 2026 ',
    copyrightPart2: '. All Rights Reserved',
    appEyebrow: 'NeoBank mobile',
    appTitle: 'Download the app and track your actions with comfort.',
    appDesc: 'Manage daily banking in one place: monitor balances, card activity, cashback, deposits and support updates with a calmer mobile experience.',
    feat1Title: 'Track actions',
    feat1Text: 'See payments, transfers and cashback in one place.',
    feat2Title: 'Control cards',
    feat2Text: 'Freeze cards and check limits anytime.',
    feat3Title: 'Stay updated',
    feat3Text: 'Follow deposits, loans and support updates faster.',
    emailNotFound: 'Email address not found in our database.',
    verifyCodeTitle: 'Enter verification code',
    verifyCodeDesc: 'We sent a 4-digit code to your email. Enter it below to subscribe.',
    verifyBtn: 'Verify',
    unsubscribeConfirmTitle: 'Unsubscribe',
    unsubscribeConfirmDesc: 'You are already subscribed. Do you want to unsubscribe?',
    yesBtn: 'Yes',
    noBtn: 'No',
    subSuccess: 'Successfully subscribed to the newsletter!',
    unsubSuccess: 'Successfully unsubscribed from the newsletter.',
    errorOccurred: 'An error occurred. Please try again.'
  },
  az: {
    contactUs: 'Əlaqə',
    address: 'Ünvan',
    addressValue: 'Bakı, Azərbaycan',
    mailUs: 'E-poçt',
    phone: 'Telefon',
    products: 'Məhsullar',
    cards: 'Kartlar',
    loans: 'Kreditlər',
    deposits: 'Depozitlər',
    cashback: 'Kəşbək',
    information: 'Məlumat',
    home: 'Ana səhifə',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    support: 'Dəstək',
    subscribe: 'Abunə ol',
    emailPlaceholder: 'E-poçt ünvanı',
    subscribeBtn: 'Abunə ol',
    copyrightPart1: 'Müəllif hüquqları © 2026 ',
    copyrightPart2: '. Bütün hüquqlar qorunur',
    appEyebrow: 'NeoBank mobil',
    appTitle: 'Tətbiqi yükləyin və əməliyyatlarınızı rahatlıqla izləyin.',
    appDesc: 'Gündəlik bankçılığı bir yerdə idarə edin: balansları, kart fəallığını, kəşbəki, depozitləri və dəstək yeniləmələrini daha rahat mobil təcrübə ilə izləyin.',
    feat1Title: 'Əməliyyatları izləyin',
    feat1Text: 'Ödənişləri, köçürmələri və kəşbəki bir yerdə görün.',
    feat2Title: 'Kartlara nəzarət',
    feat2Text: 'İstənilən vaxt kartları dondurun və limitləri yoxlayın.',
    feat3Title: 'Yeniliklərdən xəbərdar olun',
    feat3Text: 'Depozit, kredit və dəstək yeniləmələrini daha sürətli izləyin.',
    emailNotFound: 'E-poçt ünvanı bazamızda tapılmadı.',
    verifyCodeTitle: 'Təsdiq kodunu daxil edin',
    verifyCodeDesc: 'E-poçt ünvanınıza 4 rəqəmli kod göndərdik. Abunə olmaq üçün onu aşağıya daxil edin.',
    verifyBtn: 'Təsdiqlə',
    unsubscribeConfirmTitle: 'Abunəliyi ləğv et',
    unsubscribeConfirmDesc: 'Siz artıq abunəsiniz. Abunəliyi ləğv etmək istəyirsiniz?',
    yesBtn: 'Bəli',
    noBtn: 'Xeyr',
    subSuccess: 'Xəbər bülleteninə uğurla abunə oldunuz!',
    unsubSuccess: 'Xəbər bülletenindən uğurla ayrıldınız.',
    errorOccurred: 'Xəta baş verdi. Zəhmət olmasa bir daha cəhd edin.'
  },
  ru: {
    contactUs: 'Контакты',
    address: 'Адрес',
    addressValue: 'Баку, Азербайджан',
    mailUs: 'Написать нам',
    phone: 'Телефон',
    products: 'Продукты',
    cards: 'Карты',
    loans: 'Кредиты',
    deposits: 'Вклады',
    cashback: 'Кэшбэк',
    information: 'Информация',
    home: 'Главная',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    support: 'Поддержка',
    subscribe: 'Подписаться',
    emailPlaceholder: 'Адрес эл. почты',
    subscribeBtn: 'Подписаться',
    copyrightPart1: 'Авторские права © 2026 ',
    copyrightPart2: '. Все права защищены',
    appEyebrow: 'NeoBank мобильный',
    appTitle: 'Скачайте приложение и контролируйте финансы с комфортом.',
    appDesc: 'Управляйте ежедневным банкингом в одном месте: отслеживайте балансы, действия по картам, кэшбэк, вклады и обращения в поддержку.',
    feat1Title: 'Отслеживайте операции',
    feat1Text: 'Смотрите платежи, переводы и кэшбэк в одном месте.',
    feat2Title: 'Управляйте картами',
    feat2Text: 'Замораживайте карты и проверяйте лимиты в любое время.',
    feat3Title: 'Будьте в курсе',
    feat3Text: 'Следите за депозитами, кредитами и обновлениями поддержки.',
    emailNotFound: 'Электронная почта не найдена в нашей базе данных.',
    verifyCodeTitle: 'Введите код подтверждения',
    verifyCodeDesc: 'Мы отправили 4-значный код на вашу электронную почту. Введите его ниже, чтобы подписаться.',
    verifyBtn: 'Подтвердить',
    unsubscribeConfirmTitle: 'Отписаться',
    unsubscribeConfirmDesc: 'Вы уже подписаны. Хотите отписаться?',
    yesBtn: 'Да',
    noBtn: 'Нет',
    subSuccess: 'Вы успешно подписались на рассылку!',
    unsubSuccess: 'Вы успешно отписались от рассылки.',
    errorOccurred: 'Произошла ошибка. Пожалуйста, попробуйте еще раз.'
  }
}
