export const supportLang = {
  en: {
    navHome: 'Home',
    navCards: 'Cards',
    navLoans: 'Loans',
    navDeposits: 'Deposits',
    navCashback: 'Cashback',
    signIn: 'Sign in',
    openAccount: 'Open account',
    heroEyebrow: 'NeoBank Support',
    heroTitle: 'Human help, fast responses, and clear answers.',
    openTicket: 'Open support ticket',
    enterChat: 'Enter chat',
    startChat: 'Start live chat',
    stat0Label: 'Average response',
    stat0Sub: 'Fastest care',
    stat1Label: 'Resolution rate',
    stat1Sub: 'First contact',
    stat2Label: 'Availability',
    stat2Sub: 'All year round',
    stat3Label: 'Satisfaction',
    stat3Sub: 'User rated',
    mediaCopy: 'Need help with payments, card limits, or account access? Contact our team 24/7.',
    ticketsEyebrow: 'Support channels',
    ticketsTitle: 'Get assistance the way you prefer.',
    channelsDesc: 'Whether you need to report a lost card, verify a transfer, or configure deposit options, our support team provides dedicated assistance across multiple secure channels.',
    faqQ1: 'Online support',
    faqTitle1: 'Instant Chat Support',
    faqA1: 'Submit queries directly from your dashboard and track responses in real-time. Average response under 2 minutes.',
    faqQ2: 'Hotline',
    faqTitle2: 'Card Security Hotline',
    faqA2: 'Block a lost card, replace an active card, or configure transaction limits directly. Available instantly 24/7.',
    faqQ3: 'Automation',
    faqTitle3: 'Official Telegram Bot',
    faqA3: 'Get instant transaction alerts, check account balances, and locate nearest ATMs via our secure bot.',
    faqQ4: 'Direct contact',
    faqTitle4: 'Email Assistance',
    faqA4: 'For official documents, business account inquiries, or detailed feedback, write to support@neobank.az.',
    ctaEyebrow: 'Still have questions?',
    ctaTitle: 'Our support specialists are always here to help.',
    createTicketTitle: 'Create a Support Ticket',
    createTicketDesc: 'Fill out the form below and our support specialists will respond promptly.',
    yourName: 'Your Name',
    category: 'Category',
    selectCategory: 'Select a category',
    catAccount: 'Account & Profile',
    catCards: 'Cards & Limits',
    catTransactions: 'Payments & Transfers',
    catLoans: 'Loans & Deposits',
    catOther: 'Other inquiry',
    message: 'Message',
    messagePlaceholder: 'Describe your issue or question in detail...',
    submitTicket: 'Submit Ticket',
    liveChatTitle: 'Live Support Chat',
    chatInputPlaceholder: 'Type your message...',
    send: 'Send'
  },
  az: {
    navHome: 'Ana səhifə',
    navCards: 'Kartlar',
    navLoans: 'Kreditlər',
    navDeposits: 'Depozitlər',
    navCashback: 'Kəşbək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    heroEyebrow: 'NeoBank Dəstək',
    heroTitle: 'İnsan köməyi, sürətli cavablar və aydın həllər.',
    openTicket: 'Dəstək bileti açın',
    enterChat: 'Çata daxil ol',
    startChat: 'Canlı çata başlayın',
    stat0Label: 'Orta cavab vaxtı',
    stat0Sub: 'Ən sürətli xidmət',
    stat1Label: 'Həll faizi',
    stat1Sub: 'İlk əlaqə',
    stat2Label: 'Əlçatanlıq',
    stat2Sub: 'Bütün il boyu',
    stat3Label: 'Məmnuniyyət',
    stat3Sub: 'İstifadəçi qiyməti',
    mediaCopy: 'Ödənişlər, kart limitləri və ya hesaba giriş haqqında köməyə ehtiyacınız var? 24/7 komandamızla əlaqə saxlayın.',
    ticketsEyebrow: 'Dəstək kanalları',
    ticketsTitle: 'Üstünlük verdiyiniz şəkildə kömək alın.',
    channelsDesc: 'İtirilmiş kartı bildirmək, köçürməni təsdiqləmək və ya depozit variantlarını tənzimləmək lazım olub-olmamasından asılı olmayaraq, dəstək qrupumuz çoxsaylı təhlükəsiz kanallar vasitəsilə xüsusi yardım göstərir.',
    faqQ1: 'Onlayn dəstək',
    faqTitle1: 'Sürətli Çat Dəstəyi',
    faqA1: 'Sorğuları birbaşa panelinizdən göndərin və cavabları real vaxtda izləyin. Orta hesabla 2 dəqiqədən az vaxt ərzində cavab.',
    faqQ2: 'Qaynar xətt',
    faqTitle2: 'Kart Təhlükəsizliyi Qaynar Xətti',
    faqA2: 'İtirilmiş kartı bloklayın, aktiv kartı dəyişdirin və ya əməliyyat limitlərini birbaşa tənzimləyin. 7/24 anında mövcuddur.',
    faqQ3: 'Avtomatlaşdırma',
    faqTitle3: 'Rəsmi Telegram Botu',
    faqA3: 'Təhlükəsiz botumuz vasitəsilə ani əməliyyat xəbərdarlıqları alın, hesab qalıqlarını yoxlayın və ən yaxın bankomatları tapın.',
    faqQ4: 'Birbaşa əlaqə',
    faqTitle4: 'E-poçt Dəstəyi',
    faqA4: 'Rəsmi sənədlər, biznes hesabı sorğuları və ya ətraflı rəy üçün support@neobank.az ünvanına yazın.',
    ctaEyebrow: 'Hələ də suallarınız var?',
    ctaTitle: 'Dəstək mütəxəssislərimiz həmişə kömək etməyə hazırdır.',
    createTicketTitle: 'Dəstək Bileti Yaradın',
    createTicketDesc: 'Aşağıdakı formanı doldurun və dəstək mütəxəssislərimiz dərhal cavab versinlər.',
    yourName: 'Adınız',
    category: 'Kateqoriya',
    selectCategory: 'Kateqoriya seçin',
    catAccount: 'Hesab və Profil',
    catCards: 'Kartlar və Limitlər',
    catTransactions: 'Ödənişlər və Köçürmələr',
    catLoans: 'Kreditlər və Depozitlər',
    catOther: 'Diğər sorğu',
    message: 'Mesajınız',
    messagePlaceholder: 'Probleminizi və ya sualınızı təfərrüatlı təsvir edin...',
    submitTicket: 'Bileti Göndər',
    liveChatTitle: 'Canlı Dəstək Çatı',
    chatInputPlaceholder: 'Mesajınızı yazın...',
    send: 'Göndər'
  },
  ru: {
    navHome: 'Главная',
    navCards: 'Карты',
    navLoans: 'Кредиты',
    navDeposits: 'Вклады',
    navCashback: 'Кэшбэк',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    heroEyebrow: 'Поддержка NeoBank',
    heroTitle: 'Быстрые ответы и профессиональная помощь 24/7.',
    openTicket: 'Создать обращение',
    enterChat: 'Войти в чат',
    startChat: 'Открыть онлайн-чат',
    stat0Label: 'Средний ответ',
    stat0Sub: 'быстрая забота',
    stat1Label: 'Решение вопросов',
    stat1Sub: 'с первого обращения',
    stat2Label: 'Доступность',
    stat2Sub: 'круглосуточно 24/7',
    stat3Label: 'Оценка службы',
    stat3Sub: 'по отзывам',
    mediaCopy: 'Нужна помощь с платежами, картами или доступом в кабинет? Мы на связи 24 часа в сутки.',
    ticketsEyebrow: 'Каналы связи',
    ticketsTitle: 'Выберите удобный способ связи.',
    channelsDesc: 'Нужно сообщить об утере карты, проверить перевод или настроить депозит? Наша команда предлагает поддержку по нескольким безопасным каналам.',
    faqQ1: 'Онлайн поддержка',
    faqTitle1: 'Мгновенный чат',
    faqA1: 'Задавайте вопросы прямо из панели управления и получайте ответы в реальном времени. В среднем за 2 минуты.',
    faqQ2: 'Горячая линия',
    faqTitle2: 'Горячая линия безопасности',
    faqA2: 'Заблокировать карту, перевыпустить или настроить лимиты напрямую. Доступно мгновенно круглосуточно.',
    faqQ3: 'Автоматизация',
    faqTitle3: 'Официальный Telegram Бот',
    faqA3: 'Получайте уведомления об операциях, проверяйте баланс и находите банкоматы через безопасного бота.',
    faqQ4: 'Прямой контакт',
    faqTitle4: 'Помощь по Email',
    faqA4: 'Для официальных документов, корпоративных счетов или отзывов пишите на support@neobank.az.',
    ctaEyebrow: 'Остались вопросы?',
    ctaTitle: 'Наши специалисты всегда готовы помочь.',
    createTicketTitle: 'Создать заявку в поддержку',
    createTicketDesc: 'Заполните форму, и наши специалисты свяжутся с вами в ближайшее время.',
    yourName: 'Ваше имя',
    category: 'Категория',
    selectCategory: 'Выберите категорию',
    catAccount: 'Аккаунт и профиль',
    catCards: 'Карты и лимиты',
    catTransactions: 'Платежи и переводы',
    catLoans: 'Кредиты и вклады',
    catOther: 'Другой вопрос',
    message: 'Сообщение',
    messagePlaceholder: 'Опишите ваш вопрос или возникшую проблему...',
    submitTicket: 'Отправить заявку',
    liveChatTitle: 'Чат поддержки онлайн',
    chatInputPlaceholder: 'Введите сообщение...',
    send: 'Отправить'
  }
}
