export const supportLang = {
  en: {
    navHome: 'Home',
    navCards: 'Cards',
    navLoans: 'Loans',
    navDeposits: 'Deposits',
    navCashback: 'Cashback',
    signIn: 'Sign in',
    openAccount: 'Open account',
    heroEyebrow: 'NeoBank Support',
    heroTitle: 'Human help, fast responses, and clear answers.',
    openTicket: 'Open support ticket',
    startChat: 'Start live chat',
    stat0Label: 'Average response',
    stat0Sub: 'Fastest care',
    stat1Label: 'Resolution rate',
    stat1Sub: 'First contact',
    stat2Label: 'Availability',
    stat2Sub: 'All year round',
    stat3Label: 'Satisfaction',
    stat3Sub: 'User rated',
    mediaCopy: 'Need help with payments, card limits, or account access? Contact our team 24/7.',
    ticketsEyebrow: 'Support channels',
    ticketsTitle: 'Get assistance the way you prefer.',
    createTicketTitle: 'Create a Support Ticket',
    createTicketDesc: 'Fill out the form below and our support specialists will respond promptly.',
    yourName: 'Your Name',
    category: 'Category',
    selectCategory: 'Select a category',
    catAccount: 'Account & Profile',
    catCards: 'Cards & Limits',
    catTransactions: 'Payments & Transfers',
    catLoans: 'Loans & Deposits',
    catOther: 'Other inquiry',
    message: 'Message',
    messagePlaceholder: 'Describe your issue or question in detail...',
    submitTicket: 'Submit Ticket',
    liveChatTitle: 'Live Support Chat',
    chatInputPlaceholder: 'Type your message...',
    send: 'Send'
  },
  az: {
    navHome: 'Ana səhifə',
    navCards: 'Kartlar',
    navLoans: 'Kreditlər',
    navDeposits: 'Depozitlər',
    navCashback: 'Kəşbək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    heroEyebrow: 'NeoBank Dəstək',
    heroTitle: 'İnsan köməyi, sürətli cavablar və aydın həllər.',
    openTicket: 'Dəstək bileti açın',
    startChat: 'Canlı çata başlayın',
    stat0Label: 'Orta cavab vaxtı',
    stat0Sub: 'Ən sürətli xidmət',
    stat1Label: 'Həll faizi',
    stat1Sub: 'İlk əlaqə',
    stat2Label: 'Əlçatanlıq',
    stat2Sub: 'Bütün il boyu',
    stat3Label: 'Məmnuniyyət',
    stat3Sub: 'İstifadəçi qiyməti',
    mediaCopy: 'Ödənişlər, kart limitləri və ya hesaba giriş haqqında köməyə ehtiyacınız var? 24/7 komandamızla əlaqə saxlayın.',
    ticketsEyebrow: 'Dəstək kanalları',
    ticketsTitle: 'Üstünlük verdiyiniz şəkildə kömək alın.',
    createTicketTitle: 'Dəstək Bileti Yaradın',
    createTicketDesc: 'Aşağıdakı formanı doldurun və dəstək mütəxəssislərimiz dərhal cavab versinlər.',
    yourName: 'Adınız',
    category: 'Kateqoriya',
    selectCategory: 'Kateqoriya seçin',
    catAccount: 'Hesab və Profil',
    catCards: 'Kartlar və Limitlər',
    catTransactions: 'Ödənişlər və Köçürmələr',
    catLoans: 'Kreditlər və Depozitlər',
    catOther: 'Diğər sorğu',
    message: 'Mesajınız',
    messagePlaceholder: 'Probleminizi və ya sualınızı təfərrüatlı təsvir edin...',
    submitTicket: 'Bileti Göndər',
    liveChatTitle: 'Canlı Dəstək Çatı',
    chatInputPlaceholder: 'Mesajınızı yazın...',
    send: 'Göndər'
  },
  ru: {
    navHome: 'Главная',
    navCards: 'Карты',
    navLoans: 'Кредиты',
    navDeposits: 'Вклады',
    navCashback: 'Кэшбэк',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    heroEyebrow: 'Поддержка NeoBank',
    heroTitle: 'Быстрые ответы и профессиональная помощь 24/7.',
    openTicket: 'Создать обращение',
    startChat: 'Открыть онлайн-чат',
    stat0Label: 'Средний ответ',
    stat0Sub: 'быстрая забота',
    stat1Label: 'Решение вопросов',
    stat1Sub: 'с первого обращения',
    stat2Label: 'Доступность',
    stat2Sub: 'круглосуточно 24/7',
    stat3Label: 'Оценка службы',
    stat3Sub: 'по отзывам',
    mediaCopy: 'Нужна помощь с платежами, картами или доступом в кабинет? Мы на связи 24 часа в сутки.',
    ticketsEyebrow: 'Каналы связи',
    ticketsTitle: 'Выберите удобный способ связи.',
    createTicketTitle: 'Создать заявку в поддержку',
    createTicketDesc: 'Заполните форму, и наши специалисты свяжутся с вами в ближайшее время.',
    yourName: 'Ваше имя',
    category: 'Категория',
    selectCategory: 'Выберите категорию',
    catAccount: 'Аккаунт и профиль',
    catCards: 'Карты и лимиты',
    catTransactions: 'Платежи и переводы',
    catLoans: 'Кредиты и вклады',
    catOther: 'Другой вопрос',
    message: 'Сообщение',
    messagePlaceholder: 'Опишите ваш вопрос или возникшую проблему...',
    submitTicket: 'Отправить заявку',
    liveChatTitle: 'Чат поддержки онлайн',
    chatInputPlaceholder: 'Введите сообщение...',
    send: 'Отправить'
  }
}
