export const loansLang = {
  en: {
    navHome: 'Home',
    navCards: 'Cards',
    navDeposits: 'Deposits',
    navCashback: 'Cashback',
    navSupport: 'Support',
    signIn: 'Sign in',
    openAccount: 'Open account',
    heroEyebrow: 'NeoBank Loans',
    heroTitle: 'Start with a clear rate and a payment you can plan.',
    calculatePayment: 'Calculate payment',
    applyNow: 'Apply now',
    stat0Label: 'Starting rate',
    stat0Sub: 'annual rate',
    stat1Label: 'Decision time',
    stat1Sub: 'pre-check',
    stat2Label: 'Maximum term',
    stat2Sub: 'flexible schedule',
    stat3Label: 'Early payment',
    stat3Sub: 'extra fee',
    mediaCopy: 'Choose the amount, compare loan types, and move from estimate to application without losing the overview of your monthly commitment.',
    optionsEyebrow: 'Loan options',
    optionsTitle: 'Pick the purpose, then tune the numbers.',
    optionsDesc: 'NeoBank keeps the loan journey transparent: product, rate, payment, term, and application path are visible from the same page.',
    amountLabel: 'Amount',
    termLabel: 'Term',
    months: 'months',
    rateLabel: 'Rate:',
    perYear: 'per year',
    monthlyPayment: 'Monthly payment',
    totalRepayment: 'Total repayment',
    totalOverpayment: 'Total overpayment',
    takeLoan: 'Take a loan',
    selectCardTitle: 'Select payout card',
    selectCardDesc: 'Choose the card where your loan funds will be deposited instantly.',
    balance: 'Balance',
    confirmPayout: 'Confirm & Receive Funds',
    cancel: 'Cancel',
    processingTitle: 'Processing your loan...',
    processingDesc: 'We are securing your rate and transferring funds to your selected card.',
    successTitle: 'Loan Approved & Credited!',
    successDesc: 'The funds have been added to your card balance.',
    goToDashboard: 'Go to Dashboard',
    personalLoan: 'Personal loan',
    personalDesc: 'Flexible financing for purchases, travel, repairs, or planned expenses.',
    autoLoan: 'Auto loan',
    autoDesc: 'Finance a new or used car with predictable monthly payments.',
    businessLoan: 'Business loan',
    businessDesc: 'Support equipment, inventory, cash flow, and growth plans.',
    upTo30k: 'up to 30,000 AZN',
    upTo60k: 'up to 60,000 AZN',
    upTo100k: 'up to 100,000 AZN'
  },
  az: {
    navHome: 'Ana səhifə',
    navCards: 'Kartlar',
    navDeposits: 'Depozitlər',
    navCashback: 'Kəşbək',
    navSupport: 'Dəstək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    heroEyebrow: 'NeoBank Kreditləri',
    heroTitle: 'Aydın faiz dərəcəsi və planlaşdıra biləcəyiniz ödənişlə başlayın.',
    calculatePayment: 'Ödənişi hesabla',
    applyNow: 'Müraciət et',
    stat0Label: 'Başlanğıc faiz',
    stat0Sub: 'illik dərəcə',
    stat1Label: 'Qərar vaxtı',
    stat1Sub: 'ön yoxlama',
    stat2Label: 'Maksimum müddət',
    stat2Sub: 'çevik qrafik',
    stat3Label: 'Erkən ödəniş',
    stat3Sub: 'əlavə komissiya',
    mediaCopy: 'Məbləği seçin, kredit növlərini müqayisə edin və aylıq öhdəliyinizin icmalını itirmədən müraciətə keçin.',
    optionsEyebrow: 'Kredit seçimləri',
    optionsTitle: 'Məqsədi seçin, sonra rəqəmləri tənzimləyin.',
    optionsDesc: 'NeoBank kredit prosesini şəffaf saxlayır: məhsul, faiz dərəcəsi, ödəniş, müddət və müraciət yolu eyni səhifədən görünür.',
    amountLabel: 'Məbləğ',
    termLabel: 'Müddət',
    months: 'ay',
    rateLabel: 'Faiz dərəcəsi:',
    perYear: 'illik',
    monthlyPayment: 'Aylıq ödəniş',
    totalRepayment: 'Ümumi ödəniş',
    totalOverpayment: 'Ümumi artıq ödəniş',
    takeLoan: 'Kredit götür',
    selectCardTitle: 'Ödəniş kartını seçin',
    selectCardDesc: 'Kredit vəsaitlərinin anında köçürüləcəyi kartı seçin.',
    balance: 'Balans',
    confirmPayout: 'Təsdiqlə və pulu al',
    cancel: 'Ləğv et',
    processingTitle: 'Kreditiniz emal olunur...',
    processingDesc: 'Faiz dərəcənizi təsbit edirik və vəsaitləri seçilmiş karta köçürürük.',
    successTitle: 'Kredit təsdiqləndi və köçürüldü!',
    successDesc: 'Vəsaitlər kart balansınıza əlavə edildi.',
    goToDashboard: 'İdarə panelinə keç',
    personalLoan: 'Fərdi kredit',
    personalDesc: 'Alış-veriş, səyahət, təmir və ya planlaşdırılan xərclər üçün çevik maliyyələşdirmə.',
    autoLoan: 'Avto kredit',
    autoDesc: 'Proqnozlaşdırılan aylıq ödənişlərlə yeni və ya işlənmiş avtomobili maliyyələşdirin.',
    businessLoan: 'Biznes krediti',
    businessDesc: 'Avara, avadanlıq, dövriyyə və böyümə planlarını dəstəkləyin.',
    upTo30k: '30,000 AZN-dək',
    upTo60k: '60,000 AZN-dək',
    upTo100k: '100,000 AZN-dək'
  },
  ru: {
    navHome: 'Главная',
    navCards: 'Карты',
    navDeposits: 'Вклады',
    navCashback: 'Кэшбэк',
    navSupport: 'Поддержка',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    heroEyebrow: 'Кредиты NeoBank',
    heroTitle: 'Начните с прозрачной ставки и предсказуемого платежа.',
    calculatePayment: 'Рассчитать платеж',
    applyNow: 'Подать заявку',
    stat0Label: 'Начальная ставка',
    stat0Sub: 'годовая ставка',
    stat1Label: 'Решение за',
    stat1Sub: 'предварительно',
    stat2Label: 'Макс. срок',
    stat2Sub: 'гибкий график',
    stat3Label: 'Досрочное погашение',
    stat3Sub: 'комиссия',
    mediaCopy: 'Выберите сумму, сравните типы кредитов и перейдите к заявке без лишней бумажной волокиты.',
    optionsEyebrow: 'Варианты кредита',
    optionsTitle: 'Выберите цель и настройте параметры.',
    optionsDesc: 'NeoBank обеспечивает полную прозрачность: ставка, платеж, срок и оформление видны на одной странице.',
    amountLabel: 'Сумма',
    termLabel: 'Срок',
    months: 'мес.',
    rateLabel: 'Ставка:',
    perYear: 'в год',
    monthlyPayment: 'Ежемесячный платеж',
    totalRepayment: 'Итого к выплате',
    totalOverpayment: 'Переплата',
    takeLoan: 'Взять кредит',
    selectCardTitle: 'Выберите карту для зачисления',
    selectCardDesc: 'Укажите карту NeoBank, на которую будут зачислены кредитные средства.',
    balance: 'Баланс',
    confirmPayout: 'Подтвердить и получить',
    cancel: 'Отмена',
    processingTitle: 'Оформляем кредит...',
    processingDesc: 'Фиксируем процентную ставку и переводим средства на вашу карту.',
    successTitle: 'Кредит одобрен и зачислен!',
    successDesc: 'Средства успешно поступили на баланс вашей карты.',
    goToDashboard: 'Перейти в кабинет',
    personalLoan: 'Потребительский кредит',
    personalDesc: 'Гибкие средства на покупки, путешествия, ремонт или другие цели.',
    autoLoan: 'Автокредит',
    autoDesc: 'Финансирование нового или подержанного авто с прозрачным графиком.',
    businessLoan: 'Кредит для бизнеса',
    businessDesc: 'Поддержка закупки оборудования, пополнения оборотных средств и роста.',
    upTo30k: 'до 30,000 AZN',
    upTo60k: 'до 60,000 AZN',
    upTo100k: 'до 100,000 AZN'
  }
}
