export const dashboardLang = {
  en: {
    welcome: 'Welcome back',
    totalBalance: 'Total Balance',
    expenses: 'Total Expenses',
    income: 'Total Income',
    bonuses: 'Bonuses & Cashback',
    cashback: 'Cashback',
    vat: 'VAT refund',
    quickTransfer: 'Quick Transfer',
    sendMoney: 'Send Money',
    recentTransactions: 'Recent Transactions',
    spendingAnalytics: 'Spending Analytics',
    period24h: '24h',
    period7d: '7 days',
    periodMonth: 'Month',
    shopping: 'Shopping',
    food: 'Food & Dining',
    transport: 'Transport',
    entertainment: 'Entertainment',
    utilities: 'Utilities'
  },
  az: {
    welcome: 'Xoş gəldiniz',
    totalBalance: 'Ümumi Balans',
    expenses: 'Ümumi Xərclər',
    income: 'Ümumi Gəlir',
    bonuses: 'Bonuslar və Kəşbək',
    cashback: 'Kəşbək',
    vat: 'ƏDV geri al',
    quickTransfer: 'Sürətli Köçürmə',
    sendMoney: 'Pul Göndər',
    recentTransactions: 'Son Əməliyyatlar',
    spendingAnalytics: 'Xərc Təhlili',
    period24h: '24 saat',
    period7d: '7 gün',
    periodMonth: 'Ay',
    shopping: 'Alış-veriş',
    food: 'Yemək və Restoran',
    transport: 'Nəqliyyat',
    entertainment: 'Əyləncə',
    utilities: 'Kommunal'
  },
  ru: {
    welcome: 'С возвращением',
    totalBalance: 'Общий баланс',
    expenses: 'Всего расходов',
    income: 'Всего доходов',
    bonuses: 'Бонусы и кэшбэк',
    cashback: 'Кэшбэк',
    vat: 'Возврат НДС',
    quickTransfer: 'Быстрый перевод',
    sendMoney: 'Отправить',
    recentTransactions: 'Последние операции',
    spendingAnalytics: 'Аналитика расходов',
    period24h: '24 часа',
    period7d: '7 дней',
    periodMonth: 'Месяц',
    shopping: 'Покупки',
    food: 'Еда и рестораны',
    transport: 'Транспорт',
    entertainment: 'Развлечения',
    utilities: 'Коммунальные'
  }
}
