export const supportChatLang = {
  en: {
    agentWelcome: 'Hello! Welcome to NeoBank support. How can I help you today?',
    agentReply1: 'Thank you, we received your message. Our specialist will reply shortly.',
    agentReply2: 'Your information has been recorded. Is there anything else I can help with?',
    supportTitle: 'NeoBank Support',
    online: 'Online',
    close: 'Close',
    inputPlaceholder: 'Type your message...',
    modalTitle: 'Are you sure you want to close the chat?',
    modalDesc: 'Chat history will not be saved.',
    modalNo: 'No',
    modalYes: 'Yes, close',
    defaultUser: 'User',
    send: 'Send',
    connecting: 'Connecting...',
    pleaseWait: 'Please wait',
    inactivityWarning: 'Can I help you with anything else? If there is no reply within 1 minute, the chat will be closed.',
    rateService: 'Please rate our service',
    feedbackModalTitle: 'Please tell us why you gave a low rating',
    feedbackPlaceholder: 'Describe your issue...',
    submitFeedback: 'Submit',
    feedbackThanks: 'Thank you for your feedback!'
  },
  az: {
    agentWelcome: 'Salam! NeoBank dəstək xidmətinə xoş gəlmisiniz. Sizə necə kömək edə bilərəm?',
    agentReply1: 'Təşəkkür edirik, mesajınızı aldıq. Tezliklə mütəxəssisimiz sizə cavab verəcək.',
    agentReply2: 'Məlumatınız qeydə alındı. Kömək edə biləcəyim başqa bir şey var?',
    supportTitle: 'NeoBank Dəstək',
    online: 'Onlayn',
    close: 'Bağla',
    inputPlaceholder: 'Mesajınızı yazın...',
    modalTitle: 'Çatı bağlamaq istədiyinizə əminsiniz?',
    modalDesc: 'Söhbət tarixçəsi saxlanılmayacaq.',
    modalNo: 'Xeyr',
    modalYes: 'Bəli, bağla',
    defaultUser: 'İstifadəçi',
    send: 'Göndər',
    connecting: 'Qoşulur...',
    pleaseWait: 'Zəhmət olmasa gözləyin',
    inactivityWarning: 'Sizə başqa necə kömək edə bilərəm? Əgər 1 dəqiqə ərzində cavab verilməsə, söhbət bağlanacaq.',
    rateService: 'Zəhmət olmasa xidmətimizi qiymətləndirin',
    feedbackModalTitle: 'Zəhmət olmasa aşağı qiymətləndirmənin səbəbini qeyd edin',
    feedbackPlaceholder: 'Probleminizi təsvir edin...',
    submitFeedback: 'Göndər',
    feedbackThanks: 'Rəyiniz üçün təşəkkürlər!'
  },
  ru: {
    agentWelcome: 'Здравствуйте! Добро пожаловать в службу поддержки NeoBank. Чем могу помочь?',
    agentReply1: 'Спасибо, мы получили ваше сообщение. Наш специалист скоро ответит вам.',
    agentReply2: 'Ваша информация записана. Могу ли я помочь чем-то еще?',
    supportTitle: 'Поддержка NeoBank',
    online: 'Онлайн',
    close: 'Закрыть',
    inputPlaceholder: 'Введите сообщение...',
    modalTitle: 'Вы уверены, что хотите закрыть чат?',
    modalDesc: 'История чата не будет сохранена.',
    modalNo: 'Нет',
    modalYes: 'Да, закрыть',
    defaultUser: 'Пользователь',
    send: 'Отправить',
    connecting: 'Подключение...',
    pleaseWait: 'Пожалуйста, подождите',
    inactivityWarning: 'Могу ли я вам ещё чем-то помочь? Если ответ не поступит в течении 1-ой минуты чат будет закрыт.',
    rateService: 'Пожалуйста, оцените наш сервис',
    feedbackModalTitle: 'Пожалуйста, укажите причину низкой оценки',
    feedbackPlaceholder: 'Опишите вашу проблему...',
    submitFeedback: 'Отправить',
    feedbackThanks: 'Спасибо за ваш отзыв!'
  }
}
