export const paymentsLang = {
  en: {
    title: 'Payments & Transfers',
    subtitle: 'Pay utilities, mobile, internet, and transfer funds instantly.',
    mobile: 'Mobile Operator',
    utilities: 'Utilities',
    internet: 'Internet & TV',
    transfers: 'Money Transfer',
    cardToCard: 'Card to Card',
    phoneTransfer: 'By Phone Number',
    accountTransfer: 'Bank Account Transfer',
    amount: 'Amount',
    recipient: 'Recipient Phone or Card Number',
    sourceCard: 'Select Source Card',
    pay: 'Pay Now',
    transferNow: 'Transfer Now',
    paymentError: 'Payment deduction error',
    paymentSuccessfulTitle: 'Payment Successful',
    providersTitle: 'Providers',
    payFromCard: 'Pay from Card',
    amountAZN: 'Amount (AZN)',
    processingPayment: 'Processing payment in Database...',
    paymentCompleted: 'Payment Completed!',
    paymentSuccessDesc1: 'Your payment of',
    paymentSuccessDesc2: 'AZN to',
    paymentSuccessDesc3: 'was successful and recorded in DB.',
    doneBtn: 'Done'
  },
  az: {
    title: 'Ödənişlər və Köçürmələr',
    subtitle: 'Kommunal, mobil, internet ödənişləri edin və anında pul köçürün.',
    mobile: 'Mobil Operatorlar',
    utilities: 'Kommunal Ödənişlər',
    internet: 'İnternet və TV',
    transfers: 'Pul Köçürmələri',
    cardToCard: 'Kartdan Karta',
    phoneTransfer: 'Telefon Nömrəsi ilə',
    accountTransfer: 'Bank Hesabına',
    amount: 'Məbləğ',
    recipient: 'Qəbul edənin telefon və ya kart nömrəsi',
    sourceCard: 'Mənbə kartı seçin',
    pay: 'İndi Ödə',
    transferNow: 'İndi Köçür',
    paymentError: 'Ödənişin silinməsində xəta',
    paymentSuccessfulTitle: 'Ödəniş Uğurludur',
    providersTitle: 'Provayderləri',
    payFromCard: 'Kartdan Ödə',
    amountAZN: 'Məbləğ (AZN)',
    processingPayment: 'Ödəniş bazada emal edilir...',
    paymentCompleted: 'Ödəniş Tamamlandı!',
    paymentSuccessDesc1: '',
    paymentSuccessDesc2: 'AZN məbləğində',
    paymentSuccessDesc3: 'üçün ödənişiniz uğurla tamamlandı və bazada qeydə alındı.',
    doneBtn: 'Hazırdır'
  },
  ru: {
    title: 'Платежи и переводы',
    subtitle: 'Оплата коммунальных услуг, связи, интернета и мгновенные переводы.',
    mobile: 'Мобильная связь',
    utilities: 'Коммунальные услуги',
    internet: 'Интернет и ТВ',
    transfers: 'Денежные переводы',
    cardToCard: 'С карты на карту',
    phoneTransfer: 'По номеру телефона',
    accountTransfer: 'На банковский счет',
    amount: 'Сумма',
    recipient: 'Номер телефона или карты получателя',
    sourceCard: 'Выберите карту списания',
    pay: 'Оплатить сейчас',
    transferNow: 'Перевести сейчас',
    paymentError: 'Ошибка списания платежа',
    paymentSuccessfulTitle: 'Оплата успешна',
    providersTitle: 'Провайдеры',
    payFromCard: 'Оплатить с карты',
    amountAZN: 'Сумма (AZN)',
    processingPayment: 'Обработка платежа в базе данных...',
    paymentCompleted: 'Оплата завершена!',
    paymentSuccessDesc1: 'Ваш платеж в размере',
    paymentSuccessDesc2: 'AZN для',
    paymentSuccessDesc3: 'успешно завершен и сохранен в БД.',
    doneBtn: 'Готово'
  }
}
