export const errorLang = {
  en: {
    goHome: 'Back to Home',
    goDashboard: 'Go to Dashboard',
    reloadPage: 'Refresh Page',
    goBack: 'Go Back',

    // 4xx Errors
    '400_title': 'Bad Request',
    '400_desc': 'The server could not understand the request due to invalid syntax or parameters.',
    '401_title': 'Unauthorized Access',
    '401_desc': 'You must be logged in to access this page or resource.',
    '402_title': 'Payment Required',
    '402_desc': 'Payment is required to complete this action or access this resource.',
    '403_title': 'Access Forbidden',
    '403_desc': 'You do not have permission to view or access this resource.',
    '404_title': 'Page Not Found',
    '404_desc': 'The page or resource you are looking for does not exist or has been moved.',
    '405_title': 'Method Not Allowed',
    '405_desc': 'The requested HTTP method is not supported for this endpoint.',
    '408_title': 'Request Timeout',
    '408_desc': 'The server timed out waiting for the request from the client.',
    '409_title': 'Data Conflict',
    '409_desc': 'The request could not be completed due to a conflict with current resource state.',
    '422_title': 'Unprocessable Entity',
    '422_desc': 'The request was well-formed but was unable to be followed due to semantic errors.',
    '429_title': 'Too Many Requests',
    '429_desc': 'You have sent too many requests in a short time. Please slow down and try again later.',
    '4xx_title': 'Client Error',
    '4xx_desc': 'An error occurred with your request. Please check the parameters and try again.',

    // 5xx Errors
    '500_title': 'Internal Server Error',
    '500_desc': 'The server encountered an internal error and was unable to complete your request.',
    '501_title': 'Not Implemented',
    '501_desc': 'The server does not support the functionality required to fulfill the request.',
    '502_title': 'Bad Gateway',
    '502_desc': 'The server received an invalid response while acting as a gateway or proxy.',
    '503_title': 'Service Unavailable',
    '503_desc': 'The server is currently unavailable due to maintenance or high load. Please try again soon.',
    '504_title': 'Gateway Timeout',
    '504_desc': 'The gateway server did not receive a timely response from the upstream server.',
    '5xx_title': 'Server Error',
    '5xx_desc': 'Something went wrong on our servers. Our technical team has been notified.',

    // Fallback
    unknown_title: 'Unexpected Error',
    unknown_desc: 'An unexpected system error occurred. Please try again later.'
  },
  az: {
    goHome: 'Ana səhifəyə',
    goDashboard: 'Şəxsi kabinetə',
    reloadPage: 'Səhifəni yenilə',
    goBack: 'Geri qayıt',

    // 4xx Errors
    '400_title': 'Yanlış Sorğu',
    '400_desc': 'Yanlış sintaksis və ya parametrlərə görə server sorğunu emal edə bilmədi.',
    '401_title': 'Avtorizasiya Tələb Olunur',
    '401_desc': 'Bu səhifəyə daxil olmaq üçün sistemə giriş etməlisiniz.',
    '402_title': 'Ödəniş Tələb Olunur',
    '402_desc': 'Bu əməliyyatı yerinə yetirmək üçün ödəniş edilməlidir.',
    '403_title': 'Giriş Qadağandır',
    '403_desc': 'Bu resursu və ya səhifəni görmək üçün icazəniz yoxdur.',
    '404_title': 'Səhifə Tapılmadı',
    '404_desc': 'Axtardığınız səhifə mövcud deyil və ya başqa ünvana köçürülüb.',
    '405_title': 'Üsul İcazə Verilmir',
    '405_desc': 'Sorğu edilən HTTP üsulu bu ünvan üçün dəstəklənmir.',
    '408_title': 'Sorğu Vaxtı Bitdi',
    '408_desc': 'Server müraciəti gözləyərkən gözləmə vaxtı başa çatdı.',
    '409_title': 'Məlumat Münaqişəsi',
    '409_desc': 'Mövcud resurs vəziyyəti ilə ziddiyyət yarandığı üçün sorğu icra olunmadı.',
    '422_title': 'Emal Olunmayan Resurs',
    '422_desc': 'Sorğu struktur olaraq düzgündür, lakin məntiqi xətalara görə icra olunmadı.',
    '429_title': 'Həddindən Çox Sorğu',
    '429_desc': 'Qısa müddətdə çoxlu sorğu göndərdiniz. Lütfən bir qədər gözləyin.',
    '4xx_title': 'İstifadəçi Xətası',
    '4xx_desc': 'Sorğunuzda xəta baş verdi. Parametrləri yoxlayıb yenidən cəhd edin.',

    // 5xx Errors
    '500_title': 'Server Daxili Xətası',
    '500_desc': 'Serverdə daxili xəta baş verdi və sorğunuzu tamamlamaq mümkün olmadı.',
    '501_title': 'Həyata Keçirilməyib',
    '501_desc': 'Server sorğunu yerinə yetirmək üçün lazım olan funksiyanı dəstəkləmir.',
    '502_title': 'Şlüz Xətası',
    '502_desc': 'Server şlüz rolunu yerinə yetirərkən yuxarı serverdən yanlış cavab aldı.',
    '503_title': 'Xidmət Əlçatan Deyil',
    '503_desc': 'Texniki profilaktika və ya yüksək yüklənmə səbəbindən server müvəqqəti əlçatan deyil.',
    '504_title': 'Şlüz Vaxtı Bitdi',
    '504_desc': 'Şlüz serveri yuxarı serverdən vaxtında cavab almadı.',
    '5xx_title': 'Server Xətası',
    '5xx_desc': 'Serverlərimizdə nasazlıq yarandı. Texniki komandamız artıq məlumatlandırılıb.',

    // Fallback
    unknown_title: 'Gözlənilməz Xəta',
    unknown_desc: 'Sistemdə gözlənilməz xəta baş verdi. Lütfən daha sonra yenidən cəhd edin.'
  },
  ru: {
    goHome: 'На главную',
    goDashboard: 'В личный кабинет',
    reloadPage: 'Обновить страницу',
    goBack: 'Назад',

    // 4xx Errors
    '400_title': 'Некорректный запрос',
    '400_desc': 'Сервер не смог обработать запрос из-за синтаксической ошибки или неверных параметров.',
    '401_title': 'Требуется авторизация',
    '401_desc': 'Для просмотра этой страницы необходимо войти в систему.',
    '402_title': 'Требуется оплата',
    '402_desc': 'Для доступа к этому ресурсу или завершения действия требуется оплата.',
    '403_title': 'Доступ запрещен',
    '403_desc': 'У вас нет прав для просмотра этого раздела или действия.',
    '404_title': 'Страница не найдена',
    '404_desc': 'Запрошенная страница не существует или была перемещена по другому адресу.',
    '405_title': 'Метод не поддерживается',
    '405_desc': 'Запрошенный HTTP-метод не поддерживается для данного адреса.',
    '408_title': 'Время ожидания истекло',
    '408_desc': 'Сервер превысил время ожидания ответа от вашего браузера.',
    '409_title': 'Конфликт данных',
    '409_desc': 'Запрос не может быть выполнен из-за конфликта с текущим состоянием ресурса.',
    '422_title': 'Ошибка обработки данных',
    '422_desc': 'Запрос сформулирован верно, но содержит семантические ошибки и не может быть выполнен.',
    '429_title': 'Слишком много запросов',
    '429_desc': 'Вы отправили слишком много запросов за короткое время. Пожалуйста, подождите немного.',
    '4xx_title': 'Ошибка клиентского запроса',
    '4xx_desc': 'Произошла ошибка при обработке вашего запроса. Проверьте данные и повторите попытку.',

    // 5xx Errors
    '500_title': 'Внутренняя ошибка сервера',
    '500_desc': 'На сервере произошла непредвиденная ошибка. Мы уже работаем над ее устранением.',
    '501_title': 'Не реализовано',
    '501_desc': 'Сервер не поддерживает функциональность, необходимую для выполнения запроса.',
    '502_title': 'Ошибка сетевого шлюза',
    '502_desc': 'Сервер получил недопустимый ответ от вышестоящего сервера.',
    '503_title': 'Сервис временно недоступен',
    '503_desc': 'Сервер временно не может обрабатывать запросы из-за обслуживания или высокой нагрузки.',
    '504_title': 'Таймаут шлюза',
    '504_desc': 'Шлюзовый сервер не получил своевременного ответа от главного сервера.',
    '5xx_title': 'Ошибка на стороне сервера',
    '5xx_desc': 'Произошел сбой на наших серверах. Наша техническая служба уже занимается проблемой.',

    // Fallback
    unknown_title: 'Непредвиденная ошибка',
    unknown_desc: 'Произошла непредвиденная системная ошибка. Пожалуйста, попробуйте позже.'
  }
}
