export const userCardsLang = {
  en: {
    title: 'My Cards & Accounts',
    subtitle: 'Manage card limits, status, and request new cards.',
    orderCard: 'Order new card',
    activeCards: 'Active Cards',
    freezeCard: 'Freeze card',
    unfreezeCard: 'Unfreeze card',
    cardDetails: 'Card Details',
    cvv: 'CVV / CVC',
    expiry: 'Expires',
    status: 'Status',
    active: 'Active',
    frozen: 'Frozen',
    cardType: 'Card Type',
    limit: 'Monthly Limit',
    loadingCards: 'Loading cards...',
    noCards: 'You have no cards yet.',
    orderFirstCard: 'Order your first card',
    availableBalance: 'Available Balance',
    transfer: 'Transfer',
    settings: 'Settings',
    cashbackCategories: 'Cashback Categories',
    totalEarned: 'Total Earned:',
    scanQrCode: 'Scan QR code',
    addNewProduct: 'Add new product',
    orderNewCardModalTitle: 'Order a new card',
    paymentNetwork: 'Payment Network',
    feePaymentBoxText: 'First month subscription fee',
    paymentMethod: 'Payment Method',
    balanceMethod: 'From existing card balance',
    stripeMethod: 'With any bank card (Stripe)',
    selectSourceCard: 'Select card to charge',
    submitCard: 'Submit order',
    submitting: 'Submitting...',
    catMetroTitle: 'Every 5th metro or bus ride',
    catMetroText: 'Calculated from the average fare across all five rides.',
    catSuperTitle: 'Supermarkets',
    catSuperText: 'Everyday grocery spending earns the highest retail rate.',
    catPharmTitle: 'Pharmacies',
    catPharmText: 'Health and pharmacy purchases are included automatically.',
    catFuelTitle: 'Fuel stations',
    catFuelText: 'Cashback for regular car expenses and fuel payments.',
    catRestTitle: 'Restaurants, cafes, sweets',
    catRestText: 'Dining, coffee, desserts, and similar food categories.',
    catClothTitle: 'Clothing and shoes',
    catClothText: 'Fashion, footwear, and wardrobe essentials.',
    catTrendTitle: 'Trendyol and Temu',
    catTrendText: 'Online marketplace purchases through popular platforms.',
    catOtherTitle: 'Other payments',
    catOtherText: 'A base reward for payments outside the main categories.',
    cardholder: 'Cardholder',
    number: 'Number',
    blockPlasticCard: 'Block Plastic Card',
    unblockPlasticCard: 'Unblock Plastic Card',
    toggleCardStatus: 'Toggle card status',
    limitAmount: 'Limit:',
    earnedAmount: 'Earned:',
    cardLimitReached: 'You already own a {cardType} card. Each user is allowed only 1 card per type.',
    insufficientFunds: 'Insufficient funds on the selected card for the first month fee ({fee} AZN).',
    cardBlockedError: 'This card is blocked and cannot be used for payment.',
    orderCardError: 'Card order error',
    stripeMockTitle: 'Stripe Checkout (Mock)',
    stripeMockDesc: 'You are about to pay {fee} AZN using Stripe.',
    payNow: 'Pay Now',
    cardNumberField: 'Card Number',
    expiryField: 'Expiry',
    cvcField: 'CVC',
    transferMoneyTitle: 'Transfer Money',
    transferOptions: 'Transfer Options',
    transferToMyAccounts: 'Transfer to my accounts',
    transferToAnyBank: 'Transfer to card of any bank',
    transferToForeignBank: 'Transfer to card of foreign bank',
    increaseLimit: 'Increase Credit Limit',
    deactivateLimit: 'Deactivate Credit Line',
    creditLimitCooldown: 'You can only change your credit limit once a month.',
    currentLimit: 'Current limit: {limit} ₼',
    creditLineLabel: 'Credit Line',
    setupGooglePay: 'Set Up Google Pay',
    cardAdded: 'Card added',
    cardDesign: 'Card Design in Google Pay',
    makeDefault: 'Make Default',
    changePinTitle: 'Set PIN / Change PIN',
    oldPin: 'Old PIN',
    newPin: 'New PIN',
    confirmNewPin: 'Confirm New PIN',
    pinNotMatch: 'PINs do not match.',
    incorrectOldPin: 'Incorrect old PIN.',
    cardNeedsPinAlert: 'Please set a PIN for this card before using it.',
    pinSuccess: 'PIN successfully updated.',
    limitsTitle: 'Limits',
    limitsDesc: 'For transfers and cash withdrawal',
    changePin: 'Change PIN Code',
    pinDesc: 'Card and app',
    securitySettings: 'Security Settings',
    securityDesc: 'Payment settings',
    manageSubscriptions: 'Manage Subscriptions',
    subscriptionsDesc: 'All services linked to the card',
    statementsAndCerts: 'Statements & Certificates',
    accountDetailsTitle: 'Account Details',
    accountDetailsDesc: 'Domestic and SWIFT',
    featureUnavailableTitle: 'Feature Unavailable',
    featureUnavailableDesc: 'This feature is currently under development and not available yet.',
    internalTransferTitle: 'Internal Transfer',
    sourceCard: 'From Card',
    destCard: 'To Card',
    transferAmount: 'Amount (AZN)',
    transferBtn: 'Transfer',
    transferSuccess: 'Transfer successful!',
    transferError: 'Transfer failed',
    selectCard: 'Select a card',
    sameCardError: 'Source and destination cards cannot be the same.',
    transferByIban: 'Transfer by IBAN',
    destIban: 'Recipient IBAN',
    ibanLabel: 'IBAN',
    swiftLabel: 'SWIFT Code',
    copyBtn: 'Copy',
    copiedBtn: 'Copied!',
    insufficientFundsShort: 'Insufficient funds on the card.',
    transferToNeoBank: 'Transfer to NeoBank card',
    neoBankTransferTitle: 'NeoBank Transfer',
    recipientCardPlaceholder: '0000 0000 0000 0000',
    invalidCardNumberError: 'Please enter a valid 16-digit card number.',
    cardNotFoundError: 'Recipient card not found.',
    activeLoans: 'Active Loans',
    loanAmount: 'Loan Amount',
    remainingBalance: 'Remaining Balance',
    monthlyPayment: 'Monthly Payment',
    interestRate: 'Interest Rate',
    termMonths: 'Term',
    noLoans: 'You have no active loans.',
    selectProductTitle: 'Select Product',
    orderCardBtn: 'Order a Card',
    takeLoanBtn: 'Take a Loan',
    openDepositBtn: 'Open a Deposit',
    loanApplicationTitle: 'Loan Application',
    depositOpeningTitle: 'Deposit Opening',
    amountLabel: 'Amount (AZN)',
    termLabel: 'Term (months)',
    targetCardLabel: 'Target Card',
    sourceCardLabel: 'Source Card',
    submitApplication: 'Submit Application',
    activeDeposits: 'Active Deposits',
    totalIncome: 'Total Income',
    noDeposits: 'You have no active deposits.',
    monthsSuffix: 'months',
    nextPaymentDate: 'Next Payment Date',
    payLoanBtn: 'Pay Monthly',
    paymentSuccess: 'Payment successful!',
    withdrawEarly: 'Withdraw early',
    withdraw: 'Withdraw',
    withdrawDepositTitle: 'Withdraw Deposit',
    withdrawDepositPenaltyWarning: 'Early withdrawal incurs a 10% penalty on the principal amount, and no interest will be paid.',
    withdrawDepositSuccess: 'Deposit successfully withdrawn!',
    withdrawDepositBtn: 'Withdraw to Card',
    neoCredit: 'NeoCredit',
    neoDeposit: 'NeoDeposit',
    statementsChoiceTitle: 'Choose Document Type',
    extractsBtn: 'Extracts / Statements',
    referencesBtn: 'References / Certificates',
    referencesModalTitle: 'Order a Document',
    selectAllCards: 'General account (All cards & actions)',
    periodLabel: 'Period',
    languageLabel: 'Language',
    sendToEmailBtn: 'Send to email',
    statementSentSuccess: 'Document sent to your email successfully!',
    threeMonths: '3 months',
    sixMonths: '6 months',
    twelveMonths: '12 months',
    arayislarModalTitle: 'Order a Certificate (Arayış)',
    certificateType: 'Certificate Type',
    certCreditLine: 'Certificate of Credit Line',
    certDebt: 'Certificate of Debt',
    certDeposits: 'Certificate of Deposits',
    certificateFee: 'Certificate Fee',
    certificateFeeValue: '10.00 AZN (will be deducted)',
    orderCertificateBtn: 'Order (10 AZN)',
    certificateSentSuccess: 'Certificate generated and sent to your email successfully!',
    selectVariantTitle: 'Choose Your Cashback Plan',
    selectVariantSubtitle: 'Select a cashback program that suits your spending habits. You can change your choice once a month.',
    variantA: 'Option A',
    variantATitle: 'Category Rewards',
    variantADesc: 'Higher cashback on specific spending categories like supermarkets, pharmacies, fuel, and more.',
    variantB: 'Option B',
    variantBTitle: 'Simple Rewards',
    variantBDesc: 'One flat cashback rate for all your purchases — simple and straightforward.',
    selectVariantBtn: 'Select this plan',
    variantChangeCooldown: 'You can change your cashback plan starting from {date}.',
    changeVariantBtn: 'Change plan'
  },
  az: {
    title: 'Kartlarım və Hesablarım',
    subtitle: 'Kart limitlərini, statusunu idarə edin və yeni kartlar sifariş edin.',
    orderCard: 'Yeni kart sifariş et',
    activeCards: 'Aktiv Kartlar',
    freezeCard: 'Karti dondur',
    unfreezeCard: 'Karti dondurmadan çıxar',
    cardDetails: 'Kart Məlumatları',
    cvv: 'CVV / CVC',
    expiry: 'Bitmə tarixi',
    status: 'Status',
    active: 'Aktiv',
    frozen: 'Dondurulub',
    cardType: 'Kart Növü',
    limit: 'Aylıq Limit',
    loadingCards: 'Kartlar yüklənir...',
    noCards: 'Sizin hələ heç bir kartınız yoxdur.',
    orderFirstCard: 'İlk kartınızı sifariş edin',
    availableBalance: 'Mövcud Balans',
    transfer: 'Köçürmə',
    settings: 'Parametrlər',
    cashbackCategories: 'Keşbək Kateqoriyaları',
    totalEarned: 'Cəmi Qazanılan:',
    scanQrCode: 'QR kodu oxut',
    addNewProduct: 'Yeni məhsul əlavə et',
    orderNewCardModalTitle: 'Yeni kart sifarişi',
    paymentNetwork: 'Ödəniş Sistemi',
    feePaymentBoxText: 'İlk ay abunə ödənişi',
    paymentMethod: 'Ödəniş üsulu',
    balanceMethod: 'Mövcud kartın balansından',
    stripeMethod: 'İstənilən bankın kartı ilə (Stripe)',
    selectSourceCard: 'Ödəniş üçün kart seçin',
    submitting: 'İcra olunur...',
    submitCard: 'Sifarişi təsdiqlə',
    catMetroTitle: 'Hər 5-ci metro və ya avtobus gedişi',
    catMetroText: 'Bütün beş gediş üzrə orta gediş haqqından hesablanır.',
    catSuperTitle: 'Supermarketlər',
    catSuperText: 'Gündəlik ərzaq xərcləri ən yüksək pərakəndə satış dərəcəsi qazandırır.',
    catPharmTitle: 'Apteklər',
    catPharmText: 'Sağlamlıq və aptek alışları avtomatik daxil edilir.',
    catFuelTitle: 'Yanacaqdoldurma məntəqələri',
    catFuelText: 'Daimi avtomobil xərcləri və yanacaq ödənişləri üçün kəşbək.',
    catRestTitle: 'Restoranlar, kafelər, şirniyyatlar',
    catRestText: 'Yemək, qəhvə, desertlər və oxşar qida kateqoriyaları.',
    catClothTitle: 'Geyim və ayaqqabı',
    catClothText: 'Moda, ayaqqabı və qarderob.',
    catTrendTitle: 'Trendyol və Temu',
    catTrendText: 'Məşhur platformalar vasitəsilə onlayn bazar alışları.',
    catOtherTitle: 'Digər ödənişlər',
    catOtherText: 'Əsas kateqoriyalardan kənar ödənişlər üçün baza mükafatı.',
    cardholder: 'Kart Sahibi',
    number: 'Nömrə',
    blockPlasticCard: 'Plastik Kartı Blokla',
    unblockPlasticCard: 'Plastik Kartın Blokunu Aç',
    toggleCardStatus: 'Kart statusunu dəyiş',
    limitAmount: 'Limit:',
    earnedAmount: 'Qazanılan:',
    cardLimitReached: 'Siz artıq {cardType} kartına sahibsiniz. Hər istifadəçiyə yalnız 1 kart növü icazə verilir.',
    insufficientFunds: 'İlk ay ödənişi üçün ({fee} AZN) seçilmiş kartda kifayət qədər vəsait yoxdur.',
    cardBlockedError: 'Bu kart bloklanıb və ödəniş üçün istifadə edilə bilməz.',
    orderCardError: 'Kart sifarişi xətası',
    stripeMockTitle: 'Stripe Ödənişi (Maket)',
    stripeMockDesc: 'Stripe vasitəsilə {fee} AZN ödəniş etmək üzrəsiniz.',
    payNow: 'İndi ödə',
    cardNumberField: 'Kartın nömrəsi',
    expiryField: 'Bitmə tarixi',
    cvcField: 'CVC',
    transferMoneyTitle: 'Pul köçürməsi',
    transferOptions: 'Köçürmə Seçimləri',
    transferToMyAccounts: 'Öz hesablarıma köçürmə',
    transferToAnyBank: 'İstənilən bankın kartına köçürmə',
    transferToForeignBank: 'Xarici bankın kartına köçürmə',
    increaseLimit: 'Kredit limitini artır',
    deactivateLimit: 'Kredit xəttini deaktiv et',
    creditLimitCooldown: 'Kredit limitini yalnız ayda bir dəfə dəyişə bilərsiniz.',
    currentLimit: 'Cari limit: {limit} ₼',
    creditLineLabel: 'Kredit xətti',
    setupGooglePay: 'Google Pay-i quraşdır',
    cardAdded: 'Kart əlavə edildi',
    cardDesign: 'Google Pay-də kartın dizaynı',
    makeDefault: 'Əsas et',
    changePinTitle: 'PİN təyin et / PİN dəyiş',
    oldPin: 'Köhnə PİN',
    newPin: 'Yeni PİN',
    confirmNewPin: 'Yeni PİN-i təsdiqləyin',
    pinNotMatch: 'PİN kodlar uyğun gəlmir.',
    incorrectOldPin: 'Köhnə PİN yanlışdır.',
    cardNeedsPinAlert: 'Lütfən istifadə etməzdən əvvəl bu kart üçün PİN təyin edin.',
    pinSuccess: 'PİN uğurla yeniləndi.',
    limitsTitle: 'Limitlər',
    limitsDesc: 'Köçürmələr və nağdlaşdırma üçün',
    changePin: 'PİN Kodu dəyiş',
    pinDesc: 'Kart və tətbiq',
    securitySettings: 'Təhlükəsizlik Parametrləri',
    securityDesc: 'Ödəniş parametrləri',
    manageSubscriptions: 'Abunəlikləri idarə et',
    subscriptionsDesc: 'Karta bağlı bütün xidmətlər',
    statementsAndCerts: 'Çıxarışlar və Arayışlar',
    accountDetailsTitle: 'Hesab Məlumatları',
    accountDetailsDesc: 'Daxili və SWIFT',
    featureUnavailableTitle: 'Funksiya əlçatmazdır',
    featureUnavailableDesc: 'Bu funksiya hazırda inkişaf etdirilir və hələ əlçatan deyil.',
    internalTransferTitle: 'Daxili Köçürmə',
    sourceCard: 'Göndərən Kart',
    destCard: 'Alan Kart',
    transferAmount: 'Məbləğ (AZN)',
    transferBtn: 'Köçür',
    transferSuccess: 'Köçürmə uğurla tamamlandı!',
    transferError: 'Köçürmə xətası',
    selectCard: 'Kart seçin',
    sameCardError: 'Göndərən və alan kart eyni ola bilməz.',
    transferByIban: 'IBAN vasitəsilə köçürmə',
    destIban: 'Qəbuledici IBAN',
    ibanLabel: 'IBAN',
    swiftLabel: 'SWIFT Kodu',
    copyBtn: 'Kopyala',
    copiedBtn: 'Kopyalandı!',
    insufficientFundsShort: 'Kartda kifayət qədər vəsait yoxdur.',
    transferToNeoBank: 'NeoBank kartına köçürmə',
    neoBankTransferTitle: 'NeoBank Köçürmə',
    recipientCardPlaceholder: '0000 0000 0000 0000',
    invalidCardNumberError: 'Zəhmət olmasa 16 rəqəmli kart nömrəsini daxil edin.',
    cardNotFoundError: 'Qəbuledici kart tapılmadı.',
    activeLoans: 'Aktiv Kreditlər',
    loanAmount: 'Kreditin Məbləği',
    remainingBalance: 'Qalıq Borc',
    monthlyPayment: 'Aylıq Ödəniş',
    interestRate: 'Faiz dərəcəsi',
    termMonths: 'Müddət',
    noLoans: 'Sizin aktiv kreditiniz yoxdur.',
    selectProductTitle: 'Məhsul Seçin',
    orderCardBtn: 'Kart Sifariş Et',
    takeLoanBtn: 'Kredit Götür',
    openDepositBtn: 'Depozit Aç',
    loanApplicationTitle: 'Kredit Müraciəti',
    depositOpeningTitle: 'Depozit Açılışı',
    amountLabel: 'Məbləğ (AZN)',
    termLabel: 'Müddət (ay)',
    targetCardLabel: 'Köçürüləcək Kart',
    sourceCardLabel: 'Ödəniş Kartı',
    submitApplication: 'Müraciəti Göndər',
    activeDeposits: 'Aktiv Depozitlər',
    totalIncome: 'Ümumi Gəlir',
    noDeposits: 'Sizin aktiv depozitiniz yoxdur.',
    monthsSuffix: 'ay',
    nextPaymentDate: 'Növbəti Ödəniş Tarixi',
    payLoanBtn: 'Aylıq Ödəniş Et',
    paymentSuccess: 'Ödəniş uğurla tamamlandı!',
    withdrawEarly: 'Müddətdən əvvəl çıxar',
    withdraw: 'Çıxar',
    withdrawDepositTitle: 'Depoziti Çıxar',
    withdrawDepositPenaltyWarning: 'Müddətdən əvvəl çıxarış zamanı əsas məbləğdən 10% cərimə tutulur və faiz gəliri ödənilmir.',
    withdrawDepositSuccess: 'Depozit uğurla çıxarıldı!',
    withdrawDepositBtn: 'Karta Çıxar',
    neoCredit: 'NeoKredit',
    neoDeposit: 'NeoDepozit',
    statementsChoiceTitle: 'Sənəd növünü seçin',
    extractsBtn: 'Çıxarışlar',
    referencesBtn: 'Arayışlar',
    referencesModalTitle: 'Sənəd sifarişi',
    selectAllCards: 'Ümumi hesab (Bütün kartlar və əməliyyatlar)',
    periodLabel: 'Müddət',
    languageLabel: 'Dil',
    sendToEmailBtn: 'E-poçta göndər',
    statementSentSuccess: 'Sənəd e-poçtunuza uğurla göndərildi!',
    threeMonths: '3 ay',
    sixMonths: '6 ay',
    twelveMonths: '12 ay',
    arayislarModalTitle: 'Arayış sifarişi',
    certificateType: 'Arayış növü',
    certCreditLine: 'Kredit xətti haqqında arayış',
    certDebt: 'Bank qarşısında borc haqqında arayış',
    certDeposits: 'Mövcud depozitlər haqqında arayış',
    certificateFee: 'Arayış rüsumu',
    certificateFeeValue: '10.00 AZN (hesabdan çıxılacaq)',
    orderCertificateBtn: 'Sifariş et (10 AZN)',
    certificateSentSuccess: 'Arayış uğurla yaradıldı və poçtunuza göndərildi!',
    selectVariantTitle: 'Kəşbək Planınızı Seçin',
    selectVariantSubtitle: 'Xərcləmə vərdişlərinizə uyğun kəşbək proqramı seçin. Seçiminizi ayda bir dəfə dəyişdirə bilərsiniz.',
    variantA: 'Variant A',
    variantATitle: 'Kateqoriya Mükafatları',
    variantADesc: 'Supermarketlər, apteklər, yanacaq və digər xüsusi kateqoriyalarda yüksək kəşbək.',
    variantB: 'Variant B',
    variantBTitle: 'Sadə Mükafatlar',
    variantBDesc: 'Bütün alış-verişləriniz üçün tək bir sabit kəşbək dərəcəsi — sadə və aydın.',
    selectVariantBtn: 'Bu planı seç',
    variantChangeCooldown: '{date} tarixindən etibarən kəşbək planınızı dəyişdirə bilərsiniz.',
    changeVariantBtn: 'Planı dəyişdir'
  },
  ru: {
    title: 'Мои карты и счета',
    subtitle: 'Управление лимитами, статусом и заказ новых карт.',
    orderCard: 'Заказать новую карту',
    activeCards: 'Активные карты',
    freezeCard: 'Заморозить карту',
    unfreezeCard: 'Разморозить карту',
    cardDetails: 'Реквизиты карты',
    cvv: 'CVV / CVC',
    expiry: 'Срок действия',
    status: 'Статус',
    active: 'Активна',
    frozen: 'Заморожена',
    cardType: 'Тип карты',
    limit: 'Ежемесячный лимит',
    loadingCards: 'Загрузка карт...',
    noCards: 'У вас пока нет оформленных карт.',
    orderFirstCard: 'Оформить первую карту',
    availableBalance: 'Доступный баланс',
    transfer: 'Перевод',
    settings: 'Настройки',
    cashbackCategories: 'Категории кэшбэка',
    totalEarned: 'Всего заработано:',
    scanQrCode: 'Сканировать QR-код',
    addNewProduct: 'Добавить новый продукт',
    orderNewCardModalTitle: 'Оформление новой карты',
    paymentNetwork: 'Платежная система',
    feePaymentBoxText: 'Оплата первого месяца подписки',
    paymentMethod: 'Способ оплаты',
    balanceMethod: 'С баланса имеющейся карты',
    stripeMethod: 'Картой любого банка (Stripe)',
    selectSourceCard: 'Выберите карту для списания',
    submitting: 'Оформление...',
    submitCard: 'Подтвердить заказ',
    catMetroTitle: 'Каждая 5-я поездка в метро или автобусе',
    catMetroText: 'Рассчитывается из средней стоимости пяти поездок.',
    catSuperTitle: 'Супермаркеты',
    catSuperText: 'Ежедневные траты на продукты приносят максимальный кэшбэк.',
    catPharmTitle: 'Аптеки',
    catPharmText: 'Покупки для здоровья и аптеки включаются автоматически.',
    catFuelTitle: 'АЗС',
    catFuelText: 'Кэшбэк на регулярные расходы на автомобиль и топливо.',
    catRestTitle: 'Рестораны, кафе, сладости',
    catRestText: 'Ужины, кофе, десерты и подобные категории.',
    catClothTitle: 'Одежда и обувь',
    catClothText: 'Мода, обувь и гардероб.',
    catTrendTitle: 'Trendyol и Temu',
    catTrendText: 'Покупки на популярных онлайн-площадках.',
    catOtherTitle: 'Прочие платежи',
    catOtherText: 'Базовый кэшбэк для платежей вне основных категорий.',
    cardholder: 'Владелец',
    number: 'Номер',
    blockPlasticCard: 'Заблокировать карту',
    unblockPlasticCard: 'Разблокировать карту',
    toggleCardStatus: 'Изменить статус карты',
    limitAmount: 'Лимит:',
    earnedAmount: 'Заработано:',
    cardLimitReached: 'Вы уже владеете картой типа {cardType}. Каждому пользователю разрешено иметь только 1 карту каждого типа.',
    insufficientFunds: 'Недостаточно средств на выбранной карте для оплаты первого месяца ({fee} AZN).',
    cardBlockedError: 'Эта карта заблокирована и не может быть использована для оплаты.',
    orderCardError: 'Ошибка оформления карты',
    stripeMockTitle: 'Оплата Stripe (Макет)',
    stripeMockDesc: 'Вы собираетесь оплатить {fee} AZN через Stripe.',
    payNow: 'Оплатить сейчас',
    cardNumberField: 'Номер карты',
    expiryField: 'Срок действия',
    cvcField: 'CVC',
    transferMoneyTitle: 'Перевод денег',
    transferOptions: 'Варианты перевода',
    transferToMyAccounts: 'Перевод на свои счета',
    transferToAnyBank: 'Перевод на карту любого банка',
    transferToForeignBank: 'Перевод на карту зарубежного банка',
    increaseLimit: 'Увеличить кредитный лимит',
    deactivateLimit: 'Деактивировать кредитную линию',
    creditLimitCooldown: 'Вы можете изменить кредитный лимит только раз в месяц.',
    currentLimit: 'Текущий лимит: {limit} ₼',
    creditLineLabel: 'Кредитная линия',
    setupGooglePay: 'Настроить Google Pay',
    cardAdded: 'Карта добавлена',
    cardDesign: 'Дизайн карты в Google Pay',
    makeDefault: 'Сделать основной',
    changePinTitle: 'Установить PIN / Изменить PIN',
    oldPin: 'Старый PIN',
    newPin: 'Новый PIN',
    confirmNewPin: 'Подтвердите новый PIN',
    pinNotMatch: 'PIN-коды не совпадают.',
    incorrectOldPin: 'Неверный старый PIN.',
    cardNeedsPinAlert: 'Пожалуйста, установите PIN для этой карты перед ее использованием.',
    pinSuccess: 'PIN успешно обновлен.',
    limitsTitle: 'Лимиты',
    limitsDesc: 'Для переводов и снятия наличных',
    changePin: 'Изменить PIN-код',
    pinDesc: 'Для карты и приложения',
    securitySettings: 'Настройки безопасности',
    securityDesc: 'Настройки платежей',
    manageSubscriptions: 'Управление подписками',
    subscriptionsDesc: 'Все сервисы, привязанные к карте',
    statementsAndCerts: 'Выписки и Справки',
    accountDetailsTitle: 'Реквизиты счета',
    accountDetailsDesc: 'Внутренние и SWIFT',
    featureUnavailableTitle: 'Функция недоступна',
    featureUnavailableDesc: 'Эта функция в настоящее время разрабатывается и пока недоступна.',
    internalTransferTitle: 'Внутренний перевод',
    sourceCard: 'С карты',
    destCard: 'На карту',
    transferAmount: 'Сумма (AZN)',
    transferBtn: 'Перевести',
    transferSuccess: 'Перевод успешно выполнен!',
    transferError: 'Ошибка перевода',
    selectCard: 'Выберите карту',
    sameCardError: 'Карта отправителя и получателя не могут совпадать.',
    transferByIban: 'Перевод по IBAN',
    destIban: 'IBAN получателя',
    ibanLabel: 'IBAN',
    swiftLabel: 'SWIFT-код',
    copyBtn: 'Копировать',
    copiedBtn: 'Скопировано!',
    insufficientFundsShort: 'Недостаточно средств на карте.',
    transferToNeoBank: 'Перевод на карту NeoBank',
    neoBankTransferTitle: 'Перевод NeoBank',
    recipientCardPlaceholder: '0000 0000 0000 0000',
    invalidCardNumberError: 'Введите корректный 16-значный номер карты.',
    cardNotFoundError: 'Карта получателя не найдена.',
    activeLoans: 'Активные кредиты',
    loanAmount: 'Сумма кредита',
    remainingBalance: 'Остаток долга',
    monthlyPayment: 'Ежемесячный платеж',
    interestRate: 'Процентная ставка',
    termMonths: 'Срок',
    noLoans: 'У вас нет активных кредитов.',
    selectProductTitle: 'Выбор продукта',
    orderCardBtn: 'Оформить карту',
    takeLoanBtn: 'Взять кредит',
    openDepositBtn: 'Открыть депозит',
    loanApplicationTitle: 'Заявка на кредит',
    depositOpeningTitle: 'Открытие депозита',
    amountLabel: 'Сумма (AZN)',
    termLabel: 'Срок (месяцев)',
    targetCardLabel: 'Карта зачисления',
    sourceCardLabel: 'Карта списания',
    submitApplication: 'Отправить заявку',
    activeDeposits: 'Активные депозиты',
    totalIncome: 'Общий доход',
    noDeposits: 'У вас нет активных депозитов.',
    monthsSuffix: 'мес.',
    nextPaymentDate: 'Дата следующего платежа',
    payLoanBtn: 'Оплатить месяц',
    paymentSuccess: 'Оплата успешно завершена!',
    withdrawEarly: 'Снять досрочно',
    withdraw: 'Снять',
    withdrawDepositTitle: 'Снятие депозита',
    withdrawDepositPenaltyWarning: 'При досрочном снятии удерживается штраф 10% от вложенной суммы, а проценты не выплачиваются.',
    withdrawDepositSuccess: 'Депозит успешно снят!',
    withdrawDepositBtn: 'Снять на карту',
    neoCredit: 'NeoКредит',
    neoDeposit: 'NeoДепозит',
    statementsChoiceTitle: 'Выберите тип документа',
    extractsBtn: 'Выписки',
    referencesBtn: 'Справки',
    referencesModalTitle: 'Заказ документа',
    selectAllCards: 'Общий счет (Все карты и операции)',
    periodLabel: 'Период',
    languageLabel: 'Язык',
    sendToEmailBtn: 'Отправить на почту',
    statementSentSuccess: 'Документ успешно отправлен на вашу почту!',
    threeMonths: '3 месяца',
    sixMonths: '6 месяцев',
    twelveMonths: '12 месяцев',
    arayislarModalTitle: 'Заказ справки',
    certificateType: 'Тип справки',
    certCreditLine: 'Справка о кредитной линии',
    certDebt: 'Справка о задолженности',
    certDeposits: 'Справка о депозитах',
    certificateFee: 'Комиссия',
    certificateFeeValue: '10.00 AZN (будет списана)',
    orderCertificateBtn: 'Заказать (10 AZN)',
    certificateSentSuccess: 'Справка успешно сформирована и отправлена на вашу почту!',
    selectVariantTitle: 'Выберите план кэшбэка',
    selectVariantSubtitle: 'Выберите программу кэшбэка, которая подходит вашим привычкам. Менять выбор можно раз в месяц.',
    variantA: 'Вариант А',
    variantATitle: 'Кэшбэк по категориям',
    variantADesc: 'Повышенный кэшбэк на определённые категории: супермаркеты, аптеки, АЗС и другие.',
    variantB: 'Вариант Б',
    variantBTitle: 'Простой кэшбэк',
    variantBDesc: 'Единая ставка кэшбэка на все покупки — просто и понятно.',
    selectVariantBtn: 'Выбрать этот план',
    variantChangeCooldown: 'Вы сможете изменить план кэшбэка начиная с {date}.',
    changeVariantBtn: 'Сменить план'
  }
}
