export const userCardsLang = {
  en: {
    title: 'My Cards & Accounts',
    subtitle: 'Manage card limits, status, and request new cards.',
    orderCard: 'Order new card',
    activeCards: 'Active Cards',
    freezeCard: 'Freeze card',
    unfreezeCard: 'Unfreeze card',
    cardDetails: 'Card Details',
    cvv: 'CVV / CVC',
    expiry: 'Expires',
    status: 'Status',
    active: 'Active',
    frozen: 'Frozen',
    cardType: 'Card Type',
    limit: 'Monthly Limit',
    loadingCards: 'Loading cards...',
    noCards: 'You have no cards yet.',
    orderFirstCard: 'Order your first card',
    availableBalance: 'Available Balance',
    transfer: 'Transfer',
    settings: 'Settings',
    cashbackCategories: 'Cashback Categories',
    totalEarned: 'Total Earned:',
    scanQrCode: 'Scan QR code',
    addNewProduct: 'Add new product',
    orderNewCardModalTitle: 'Order a new card',
    paymentNetwork: 'Payment Network',
    feePaymentBoxText: 'First month subscription fee',
    paymentMethod: 'Payment Method',
    balanceMethod: 'From existing card balance',
    stripeMethod: 'With any bank card (Stripe)',
    selectSourceCard: 'Select card to charge',
    submitting: 'Processing...',
    submitCard: 'Order card',
    cardholder: 'Cardholder',
    number: 'Number',
    blockPlasticCard: 'Block Plastic Card',
    unblockPlasticCard: 'Unblock Plastic Card',
    toggleCardStatus: 'Toggle card status',
    limitAmount: 'Limit:',
    earnedAmount: 'Earned:',
    cardLimitReached: 'You already own a {cardType} card. Each user is allowed only 1 card per type.',
    insufficientFunds: 'Insufficient funds on the selected card for the first month fee ({fee} AZN).',
    orderCardError: 'Card order error'
  },
  az: {
    title: 'Kartlarım və Hesablarım',
    subtitle: 'Kart limitlərini, statusunu idarə edin və yeni kartlar sifariş edin.',
    orderCard: 'Yeni kart sifariş et',
    activeCards: 'Aktiv Kartlar',
    freezeCard: 'Karti dondur',
    unfreezeCard: 'Karti dondurmadan çıxar',
    cardDetails: 'Kart Məlumatları',
    cvv: 'CVV / CVC',
    expiry: 'Bitmə tarixi',
    status: 'Status',
    active: 'Aktiv',
    frozen: 'Dondurulub',
    cardType: 'Kart Növü',
    limit: 'Aylıq Limit',
    loadingCards: 'Kartlar yüklənir...',
    noCards: 'Sizin hələ heç bir kartınız yoxdur.',
    orderFirstCard: 'İlk kartınızı sifariş edin',
    availableBalance: 'Mövcud Balans',
    transfer: 'Köçürmə',
    settings: 'Parametrlər',
    cashbackCategories: 'Keşbək Kateqoriyaları',
    totalEarned: 'Cəmi Qazanılan:',
    scanQrCode: 'QR kodu oxut',
    addNewProduct: 'Yeni məhsul əlavə et',
    orderNewCardModalTitle: 'Yeni kart sifarişi',
    paymentNetwork: 'Ödəniş Sistemi',
    feePaymentBoxText: 'İlk ay abunə ödənişi',
    paymentMethod: 'Ödəniş üsulu',
    balanceMethod: 'Mövcud kartın balansından',
    stripeMethod: 'İstənilən bankın kartı ilə (Stripe)',
    selectSourceCard: 'Ödəniş üçün kart seçin',
    submitting: 'İcra olunur...',
    submitCard: 'Kartı sifariş et',
    cardholder: 'Kart Sahibi',
    number: 'Nömrə',
    blockPlasticCard: 'Plastik Kartı Blokla',
    unblockPlasticCard: 'Plastik Kartın Blokunu Aç',
    toggleCardStatus: 'Kart statusunu dəyiş',
    limitAmount: 'Limit:',
    earnedAmount: 'Qazanılan:',
    cardLimitReached: 'Siz artıq {cardType} kartına sahibsiniz. Hər istifadəçiyə yalnız 1 kart növü icazə verilir.',
    insufficientFunds: 'İlk ay ödənişi üçün ({fee} AZN) seçilmiş kartda kifayət qədər vəsait yoxdur.',
    orderCardError: 'Kart sifarişi xətası'
  },
  ru: {
    title: 'Мои карты и счета',
    subtitle: 'Управление лимитами, статусом и заказ новых карт.',
    orderCard: 'Заказать новую карту',
    activeCards: 'Активные карты',
    freezeCard: 'Заморозить карту',
    unfreezeCard: 'Разморозить карту',
    cardDetails: 'Реквизиты карты',
    cvv: 'CVV / CVC',
    expiry: 'Срок действия',
    status: 'Статус',
    active: 'Активна',
    frozen: 'Заморожена',
    cardType: 'Тип карты',
    limit: 'Ежемесячный лимит',
    loadingCards: 'Загрузка карт...',
    noCards: 'У вас пока нет оформленных карт.',
    orderFirstCard: 'Оформить первую карту',
    availableBalance: 'Доступный баланс',
    transfer: 'Перевод',
    settings: 'Настройки',
    cashbackCategories: 'Категории кэшбэка',
    totalEarned: 'Всего заработано:',
    scanQrCode: 'Сканировать QR-код',
    addNewProduct: 'Добавить новый продукт',
    orderNewCardModalTitle: 'Оформление новой карты',
    paymentNetwork: 'Платежная система',
    feePaymentBoxText: 'Оплата первого месяца подписки',
    paymentMethod: 'Способ оплаты',
    balanceMethod: 'С баланса имеющейся карты',
    stripeMethod: 'Картой любого банка (Stripe)',
    selectSourceCard: 'Выберите карту для списания',
    submitting: 'Оформление...',
    submitCard: 'Заказать карту',
    cardholder: 'Владелец',
    number: 'Номер',
    blockPlasticCard: 'Заблокировать карту',
    unblockPlasticCard: 'Разблокировать карту',
    toggleCardStatus: 'Изменить статус карты',
    limitAmount: 'Лимит:',
    earnedAmount: 'Заработано:',
    cardLimitReached: 'Вы уже владеете картой типа {cardType}. Каждому пользователю разрешено иметь только 1 карту каждого типа.',
    insufficientFunds: 'Недостаточно средств на выбранной карте для оплаты первого месяца ({fee} AZN).',
    orderCardError: 'Ошибка оформления карты'
  }
}
