export const landingLang = {
  en: {
    navCards: 'Cards',
    navLoans: 'Loans',
    navDeposits: 'Deposits',
    navCashback: 'Cashback',
    navSupport: 'Support',
    signIn: 'Sign in',
    openAccount: 'Open account',
    eyebrowSmarter: 'Smarter banking',
    heroTitle: 'Smarter banking. Premium glow.',
    heroCopy: 'A clean, secure banking workspace for accounts, cards, transfers, loans, deposits, cashback, and support. Designed around the NeoBank identity: sharp graphite surfaces, violet depth, and a confident gold finish.',
    getStarted: 'Get started',
    viewDashboard: 'View dashboard',
    avgSignup: 'average signup',
    accountAccess: 'account access',
    protectedLogin: 'protected login',
    eyebrowOneSurface: 'One banking surface',
    headingEverything: 'Everything important stays within reach.',
    prod0Label: 'Accounts',
    prod0Title: 'Open and organize money in minutes',
    prod0Text: 'Create everyday, savings, and goal accounts with live balance tracking.',
    prod1Label: 'Cards',
    prod1Title: 'Issue cards with controls built in',
    prod1Text: 'Freeze, replace, and manage limits before a payment ever becomes a problem.',
    prod2Label: 'Transfers',
    prod2Title: 'Move funds without the waiting room',
    prod2Text: 'Send money between your accounts or to another NeoBank customer instantly.',
    prod3Label: 'Insights',
    prod3Title: 'Know where every manat is going',
    prod3Text: 'Track categories, cashbacks, subscriptions, and upcoming commitments at a glance.',
    eyebrowControl: 'Daily control',
    headingControl: 'Less guessing. More knowing.',
    textControl: 'NeoBank keeps the operational side of money visible: balances, cards, deposits, loans, cashback, subscriptions, and support requests are grouped around the actions people actually take.',
    previewOverview: 'Account overview',
    previewDepProgress: 'Deposit progress',
    previewPremiumCard: 'Premium card',
    previewActive: 'Active',
    previewCashback: 'Cashback this month',
    eyebrowSecurity: 'Security by default',
    headingSecurity: 'Your money needs clear controls.',
    sec0: 'Two-factor authentication on every sensitive action',
    sec1: 'Instant card freezing and limit management',
    sec2: 'Support tickets tracked from request to resolution',
    eyebrowReady: 'Ready when you are',
    headingReady: 'Open your account and start banking in one place.',
    createAccount: 'Create account'
  },
  az: {
    navCards: 'Kartlar',
    navLoans: 'Kreditlər',
    navDeposits: 'Depozitlər',
    navCashback: 'Kəşbək',
    navSupport: 'Dəstək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    eyebrowSmarter: 'Ağıllı bankçılıq',
    heroTitle: 'Ağıllı bankçılıq. Premium parıltı.',
    heroCopy: 'Hesablar, kartlar, köçürmələr, kreditlər, depozitlər, kəşbək və dəstək üçün təmiz, təhlükəsiz bank iş sahəsi. NeoBank kimliyi əsasında hazırlanmışdır: kəskin qrafit səthlər, bənövşəyi dərinlik və inamlı qızılı rəng.',
    getStarted: 'Başlayın',
    viewDashboard: 'İdarə panelinə bax',
    avgSignup: 'orta qeydiyyat vaxtı',
    accountAccess: 'hesab girişi',
    protectedLogin: 'mühafizə olunan giriş',
    eyebrowOneSurface: 'Vahid bank sahəsi',
    headingEverything: 'Mühüm olan hər şey əlinizin altındadır.',
    prod0Label: 'Hesablar',
    prod0Title: 'Pullarınızı dəqiqələr ərzində açın və təşkil edin',
    prod0Text: 'Canlı balans izləməsi ilə gündəlik, əmanət və hədəf hesabları yaradın.',
    prod1Label: 'Kartlar',
    prod1Title: 'Nəzarət funksiyaları ilə kartlar buraxın',
    prod1Text: 'Ödəniş problemi yaranmadan əvvəl dondurun, dəyişdirin və limitləri idarə edin.',
    prod2Label: 'Köçürmələr',
    prod2Title: 'Vəsaitləri gözləmədən köçürün',
    prod2Text: 'Hesablarınız arasında və ya başqa NeoBank müştərisinə anında pul göndərin.',
    prod3Label: 'Təhlillər',
    prod3Title: 'Hər manatın hara getdiyini bilin',
    prod3Text: 'Kategoriyaları, kəşbəkləri, abunəlikləri və gələcək öhdəlikləri bir baxışda izləyin.',
    eyebrowControl: 'Gündəlik nəzarət',
    headingControl: 'Daha az təxmin. Daha çox dəqiqlik.',
    textControl: 'NeoBank pulun əməliyyat tərəfini aydın saxlayır: balanslar, kartlar, depozitlər, kreditlər, kəşbək, abunəliklər və dəstək müraciətləri insanların həqiqətən etdiyi hərəkətlər ətrafında qruplaşdırılıb.',
    previewOverview: 'Hesab icmalı',
    previewDepProgress: 'Depozit tərəqqisi',
    previewPremiumCard: 'Premium kart',
    previewActive: 'Aktiv',
    previewCashback: 'Bu ayki kəşbək',
    eyebrowSecurity: 'Standart təhlükəsizlik',
    headingSecurity: 'Pullarınızın aydın nəzarətə ehtiyacı var.',
    sec0: 'Hər həssas əməliyyatda ikiFA doğrulama',
    sec1: 'Anında kart dondurulması və limit idarəetməsi',
    sec2: 'Müraciətdən həllə qədər izlənilən dəstək biletləri',
    eyebrowReady: 'Hazır olduğunuzda',
    headingReady: 'Hesabınızı açın və bir yerdə bankçılığa başlayın.',
    createAccount: 'Hesab yaradın'
  },
  ru: {
    navCards: 'Карты',
    navLoans: 'Кредиты',
    navDeposits: 'Вклады',
    navCashback: 'Кэшбэк',
    navSupport: 'Поддержка',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    eyebrowSmarter: 'Умный банкинг',
    heroTitle: 'Умный банкинг. Премиальный уровень.',
    heroCopy: 'Чистая и безопасная рабочая среда для счетов, карт, переводов, кредитов, депозитов, кэшбэка и поддержки. Разработано в стиле NeoBank: строгий графит, глубокий фиолетовый и уверенный золотой акцент.',
    getStarted: 'Начать',
    viewDashboard: 'Панель управления',
    avgSignup: 'среднее время регистрации',
    accountAccess: 'доступ к счету',
    protectedLogin: 'защищенный вход',
    eyebrowOneSurface: 'Единая экосистема',
    headingEverything: 'Всё важное всегда под рукой.',
    prod0Label: 'Счета',
    prod0Title: 'Открывайте и организуйте деньги за минуты',
    prod0Text: 'Создавайте повседневные, накопительные и целевые счета с отслеживанием баланса.',
    prod1Label: 'Карты',
    prod1Title: 'Выпускайте карты со встроенным контролем',
    prod1Text: 'Замораживайте, перевыпускайте и управляйте лимитами до возникновения проблем.',
    prod2Label: 'Переводы',
    prod2Title: 'Переводите средства без ожидания',
    prod2Text: 'Мгновенно отправляйте деньги между своими счетами или другим клиентам NeoBank.',
    prod3Label: 'Аналитика',
    prod3Title: 'Знайте, куда уходит каждый манат',
    prod3Text: 'Отслеживайте категории, кэшбэк, подписки и предстоящие платежи с первого взгляда.',
    eyebrowControl: 'Ежедневный контроль',
    headingControl: 'Меньше догадок. Больше точности.',
    textControl: 'NeoBank сохраняет прозрачность финансовых операций: балансы, карты, вклады, кредиты, кэшбэк и обращения в поддержку сгруппированы вокруг реальных действий пользователей.',
    previewOverview: 'Обзор счета',
    previewDepProgress: 'Прогресс вклада',
    previewPremiumCard: 'Премиум карта',
    previewActive: 'Активна',
    previewCashback: 'Кэшбэк за этот месяц',
    eyebrowSecurity: 'Безопасность по умолчанию',
    headingSecurity: 'Вашим деньгам нужен надежный контроль.',
    sec0: 'Двухфакторная аутентификация для каждой важной операции',
    sec1: 'Мгновенная заморозка карт и управление лимитами',
    sec2: 'Отслеживание заявок в поддержку от создания до решения',
    eyebrowReady: 'Готовы начать?',
    headingReady: 'Откройте счет и управляйте финансами в одном месте.',
    createAccount: 'Создать счет'
  }
}
