export const cashbackLang = {
  en: {
    navHome: 'Home',
    navCards: 'Cards',
    navLoans: 'Loans',
    navDeposits: 'Deposits',
    navSupport: 'Support',
    signIn: 'Sign in',
    openAccount: 'Open account',
    heroEyebrow: 'NeoBank Cashback',
    heroTitle: 'Earn rewards on every daily transaction.',
    exploreCategories: 'Explore categories',
    getCard: 'Get a cashback card',
    stat0Label: 'Maximum cashback',
    stat0Sub: 'selected promo rides',
    stat1Label: 'Category rewards',
    stat1Sub: 'monthly choices',
    stat2Label: 'Base reward',
    stat2Sub: 'all other purchases',
    mediaCopy: 'Choose monthly cashback categories or enjoy simple flat rewards on all payments.',
    programEyebrow: 'Cashback Programs',
    programTitle: 'Choose how your payments earn money back.',
    cat0Title: 'Every 5th metro or bus ride',
    cat0Text: 'Calculated from the average fare across all five rides.',
    cat1Title: 'Supermarkets',
    cat1Text: 'Everyday grocery spending earns the highest retail rate.',
    cat2Title: 'Pharmacies',
    cat2Text: 'Health and pharmacy purchases are included automatically.',
    cat3Title: 'Fuel stations',
    cat3Text: 'Cashback for regular car expenses and fuel payments.',
    cat4Title: 'Restaurants, cafes, sweets',
    cat4Text: 'Dining, coffee, desserts, and similar food categories.',
    cat5Title: 'Clothing and shoes',
    cat5Text: 'Fashion, footwear, and wardrobe essentials.',
    cat6Title: 'Trendyol and Temu',
    cat6Text: 'Online marketplace purchases through popular platforms.',
    cat7Title: 'Other payments',
    cat7Text: 'A base reward for payments outside the main categories.',
    startEarning: 'Start earning cashback'
  },
  az: {
    navHome: 'Ana səhifə',
    navCards: 'Kartlar',
    navLoans: 'Kreditlər',
    navDeposits: 'Depozitlər',
    navSupport: 'Dəstək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    heroEyebrow: 'NeoBank Kəşbək',
    heroTitle: 'Hər gündəlik əməliyyatda mükafat qazanın.',
    exploreCategories: 'Kateqoriyaları kəşf et',
    getCard: 'Kəşbək kartı al',
    stat0Label: 'Maksimum kəşbək',
    stat0Sub: 'seçilmiş promolar',
    stat1Label: 'Kateqoriya mükafatları',
    stat1Sub: 'aylıq seçimlər',
    stat2Label: 'Baza mükafatı',
    stat2Sub: 'bütün digər alış-verişlər',
    mediaCopy: 'Aylıq kəşbək kateqoriyalarını seçin və ya bütün ödənişlərdə sadə sabit mükafatlardan zövq alın.',
    programEyebrow: 'Kəşbək Proqramları',
    programTitle: 'Ödənişlərinizin necə pul qaytardığını seçin.',
    cat0Title: 'Hər 5-ci metro və ya avtobus gedişi',
    cat0Text: 'Bütün beş gediş üzrə orta gediş haqqından hesablanır.',
    cat1Title: 'Supermarketlər',
    cat1Text: 'Gündəlik ərzaq xərcləri ən yüksək perakendə dərəcəsini qazanır.',
    cat2Title: 'Apteklər',
    cat2Text: 'Sağlamlıq və aptek alış-verişləri avtomatik daxil edilir.',
    cat3Title: 'Yanacaqdoldurma məntəqələri',
    cat3Text: 'Müntəzəm avtomobil xərcləri və yanacaq ödənişləri üçün kəşbək.',
    cat4Title: 'Restoranlar, kafelər, şirniyyat',
    cat4Text: 'Yemək, kofe, desertlər və bənzər qida kateqoriyaları.',
    cat5Title: 'Geyim və ayaqqabı',
    cat5Text: 'Dəb, ayaqqabı və qarderob tələbatları.',
    cat6Title: 'Trendyol və Temu',
    cat6Text: 'Məşhur platformalar vasitəsilə onlayn bazar alış-verişləri.',
    cat7Title: 'Digər ödənişlər',
    cat7Text: 'Əsas kateqoriyalardan kənar ödənişlər üçün baza mükafatı.',
    startEarning: 'Kəşbək qazanmağa başla'
  },
  ru: {
    navHome: 'Главная',
    navCards: 'Карты',
    navLoans: 'Кредиты',
    navDeposits: 'Вклады',
    navSupport: 'Поддержка',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    heroEyebrow: 'Кэшбэк NeoBank',
    heroTitle: 'Возвращайте деньги с каждой ежедневной покупки.',
    exploreCategories: 'Категории кэшбэка',
    getCard: 'Получить карту',
    stat0Label: 'Макс. кэшбэк',
    stat0Sub: 'промо поездки',
    stat1Label: 'Категории',
    stat1Sub: 'выбор каждый месяц',
    stat2Label: 'Базовый кэшбэк',
    stat2Sub: 'на все покупки',
    mediaCopy: 'Выбирайте категории кэшбэка каждый месяц или получайте гарантированный процент со всех трат.',
    programEyebrow: 'Программы кэшбэка',
    programTitle: 'Выбирайте способ начисления бонусов.',
    cat0Title: 'Каждая 5-я поездка в метро или автобусе',
    cat0Text: 'Рассчитывается от средней стоимости пяти поездок.',
    cat1Title: 'Супермаркеты',
    cat1Text: 'Покупка продуктов с высоким процентом возврата.',
    cat2Title: 'Аптеки',
    cat2Text: 'Покупки в аптеках и товары для здоровья начисляются автоматически.',
    cat3Title: 'АЗС',
    cat3Text: 'Кэшбэк за заправку автомобиля и расходы на АЗС.',
    cat4Title: 'Рестораны, кафе, кофейни',
    cat4Text: 'Обеды, кофе, десерты и заведения общественного питания.',
    cat5Title: 'Одежда и обувь',
    cat5Text: 'Обновление гардероба и покупки в магазинах одежды.',
    cat6Title: 'Trendyol и Temu',
    cat6Text: 'Онлайн-покупки на популярный маркетплейсах.',
    cat7Title: 'Другие платежи',
    cat7Text: 'Базовое вознаграждение за любые другие покупки.',
    startEarning: 'Начать получать кэшбэк'
  }
}
