export const depositsLang = {
  en: {
    navHome: 'Home',
    navCards: 'Cards',
    navLoans: 'Loans',
    navCashback: 'Cashback',
    navSupport: 'Support',
    signIn: 'Sign in',
    openAccount: 'Open account',
    heroEyebrow: 'NeoBank Deposits',
    heroTitle: 'Grow your savings with flexible terms and reliable rates.',
    calculateYield: 'Calculate yield',
    openDeposit: 'Open deposit',
    stat0Label: 'Minimum opening',
    stat0Sub: 'Start small',
    stat1Label: 'Top annual rate',
    stat1Sub: 'Premium plan',
    stat2Label: 'Flexible terms',
    stat2Sub: 'Choose maturity',
    stat3Label: 'Currencies',
    stat3Sub: 'Local and foreign',
    mediaCopy: 'Calculate income, choose monthly or end-of-term payout, and start saving with guaranteed returns.',
    calculatorEyebrow: 'Deposit calculator',
    calculatorTitle: 'Select a plan and estimate your return.',
    amountLabel: 'Deposit amount',
    termLabel: 'Term',
    months: 'months',
    expectedRate: 'Expected annual rate',
    totalIncome: 'Estimated income',
    totalBalance: 'Total at maturity',
    openDepositBtn: 'Open deposit now',
    selectCardTitle: 'Source account',
    selectCardDesc: 'Choose card or account from which funds will be transferred.',
    confirmDeposit: 'Confirm & Open Deposit',
    processingTitle: 'Opening deposit...',
    processingDesc: 'Transferring funds and activating your deposit account.',
    successTitle: 'Deposit Successfully Opened!',
    successDesc: 'Your money is now growing with NeoBank guaranteed rates.',
    done: 'Done',
    insufficientFundsError: 'Insufficient funds on the card.'
  },
  az: {
    navHome: 'Ana səhifə',
    navCards: 'Kartlar',
    navLoans: 'Kreditlər',
    navCashback: 'Kəşbək',
    navSupport: 'Dəstək',
    signIn: 'Daxil ol',
    openAccount: 'Hesab aç',
    heroEyebrow: 'NeoBank Depozitləri',
    heroTitle: 'Əmanətlərinizi çevik şərtlər və etibarlı faizlərlə artırın.',
    calculateYield: 'Gəliri hesabla',
    openDeposit: 'Depozit aç',
    stat0Label: 'Minimum məbləğ',
    stat0Sub: 'Kiçik məbləğlə başlayın',
    stat1Label: 'Maksimum illik faiz',
    stat1Sub: 'Premium plan',
    stat2Label: 'Çevik müddət',
    stat2Sub: 'Müddəti seçin',
    stat3Label: 'Valyutalar',
    stat3Sub: 'Milli və xarici',
    mediaCopy: 'Gəliri hesablayın, aylıq və ya müddətin sonunda ödənişi seçin və zəmanətli gəlirlə yığmağa başlayın.',
    calculatorEyebrow: 'Depozit kalkulyatoru',
    calculatorTitle: 'Plan seçin və gəlirinizi qiymətləndirin.',
    amountLabel: 'Depozit məbləği',
    termLabel: 'Müddət',
    months: 'ay',
    expectedRate: 'Gözlənilən illik faiz',
    totalIncome: 'Təxmini gəlir',
    totalBalance: 'Müddətin sonunda ümumi məbləğ',
    openDepositBtn: 'İndi depozit açın',
    selectCardTitle: 'Mənbə hesabı',
    selectCardDesc: 'Vəsaitin köçürüləcəyi kartı və ya hesabı seçin.',
    confirmDeposit: 'Təsdiqlə və depozit aç',
    processingTitle: 'Depozit açılır...',
    processingDesc: 'Vəsaitlər köçürülür və depozit hesabınız aktivləşdirilir.',
    successTitle: 'Depozit uğurla açıldı!',
    successDesc: 'Vəsaitiniz artıq NeoBank zəmanətli faizləri ilə artır.',
    done: 'Hazırdır',
    insufficientFundsError: 'Kartda kifayət qədər vəsait yoxdur.'
  },
  ru: {
    navHome: 'Главная',
    navCards: 'Карты',
    navLoans: 'Кредиты',
    navCashback: 'Кэшбэк',
    navSupport: 'Поддержка',
    signIn: 'Войти',
    openAccount: 'Открыть счет',
    heroEyebrow: 'Депозиты NeoBank',
    heroTitle: 'Увеличивайте накопления с гибкими условиями и высокой доходностью.',
    calculateYield: 'Рассчитать доход',
    openDeposit: 'Открыть вклад',
    stat0Label: 'Мин. взнос',
    stat0Sub: 'легкий старт',
    stat1Label: 'Макс. ставка',
    stat1Sub: 'Премиум тариф',
    stat2Label: 'Гибкие сроки',
    stat2Sub: 'выбор периода',
    stat3Label: 'Валюты',
    stat3Sub: 'AZN и USD',
    mediaCopy: 'Рассчитайте процентный доход, выберите выплату ежемесячно или в конце срока и копите с гарантированной ставкой.',
    calculatorEyebrow: 'Калькулятор вкладов',
    calculatorTitle: 'Выберите подходящую программу.',
    amountLabel: 'Сумма вклада',
    termLabel: 'Срок',
    months: 'мес.',
    expectedRate: 'Годовая ставка',
    totalIncome: 'Расчетный доход',
    totalBalance: 'Итоговая сумма',
    openDepositBtn: 'Открыть вклад сейчас',
    selectCardTitle: 'Карта для списания',
    selectCardDesc: 'Выберите карту NeoBank для перевода средств на депозитный счет.',
    confirmDeposit: 'Подтвердить и открыть',
    processingTitle: 'Открываем вклад...',
    processingDesc: 'Переводим средства и активируем депозитный счет.',
    successTitle: 'Вклад успешно открыт!',
    successDesc: 'Ваши средства уже работают и приносят гарантированный доход.',
    done: 'Готово',
    insufficientFundsError: 'Недостаточно средств на карте.'
  }
}
